### PR TITLE
Add workaround for data race bug in libstdc++

### LINKED ISSUE #7446: Data race deep within `std::regex`
I've seen one instance so far, in a TSAN build running the `jwt_test` `auto` test.

https://github.com/microsoft/CCF/actions/runs/19171291271/job/54804282250?pr=7440#step:7:1254

Trimmed trace (the full one is too bug for issue creation, apparently):

```
2025-11-07T14:48:11.8700481Z WARNING: ThreadSanitizer: data race (pid=4838)
2025-11-07T14:48:11.8700583Z   Read of size 1 at 0x7ffff789a978 by thread T7:
2025-11-07T14:48:11.8706099Z     #0 std::ctype<char>::narrow(char, char) const /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/locale_facets.h:941:6 (logging+0x200222)
2025-11-07T14:48:11.8706576Z     #1 std::__detail::_Scanner<char>::_M_scan_normal() /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_scanner.tcc:100:51 (logging+0x2008ed)
2025-11-07T14:48:11.8707146Z     #2 std::__detail::_Scanner<char>::_M_advance() /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_scanner.tcc:79:2 (logging+0x1ffd7d)
2025-11-07T14:48:11.8707778Z     #3 std::__detail::_Compiler<std::__cxx11::regex_traits<char>>::_M_match_token(std::__detail::_ScannerBase::_TokenT) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_compiler.tcc:575:15 (logging+0x1fde1b)
2025-11-07T14:48:11.8708247Z     #4 std::__detail::_Compiler<std::__cxx11::regex_traits<char>>::_M_atom() /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_compiler.tcc:330:9 (logging+0x207456)
2025-11-07T14:48:11.8708732Z     #5 std::__detail::_Compiler<std::__cxx11::regex_traits<char>>::_M_term() /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_compiler.tcc:133:17 (logging+0x2067b3)
2025-11-07T14:48:11.8709227Z     #6 std::__detail::_Compiler<std::__cxx11::regex_traits<char>>::_M_alternative() /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_compiler.tcc:115:17 (logging+0x20636c)
2025-11-07T14:48:11.8709824Z     #7 std::__detail::_Compiler<std::__cxx11::regex_traits<char>>::_M_alternative() /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_compiler.tcc:118:10 (logging+0x20639f)
2025-11-07T14:48:11.8710340Z     #8 std::__detail::_Compiler<std::__cxx11::regex_traits<char>>::_M_disjunction() /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_compiler.tcc:91:13 (logging+0x1fdc3c)
2025-11-07T14:48:11.8711092Z     #9 std::__detail::_Compiler<std::__cxx11::regex_traits<char>>::_Compiler(char const*, char const*, std::locale const&, std::regex_constants::syntax_option_type) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_compiler.tcc:76:13 (logging+0x1fd140)
2025-11-07T14:48:11.8711784Z     #10 std::__cxx11::basic_regex<char, std::__cxx11::regex_traits<char>>::_M_compile(char const*, char const*, std::regex_constants::syntax_option_type) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex.h:809:34 (logging+0x1fcd3f)
2025-11-07T14:48:11.8712405Z     #11 std::__cxx11::basic_regex<char, std::__cxx11::regex_traits<char>>::basic_regex(char const*, std::regex_constants::syntax_option_type) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex.h:473:9 (logging+0x1fc9c2)
2025-11-07T14:48:11.8712852Z     #12 http::parse_url_full(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) CCF/build/CCF/src/http/http_parser.h:150:16 (logging+0x655ba6)
2025-11-07T14:48:11.8713871Z     #13 ccf::JwtKeyAutoRefresh::refresh_jwt_keys()::'lambda'(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, ccf::JwtIssuerMetadata const&)::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, ccf::JwtIssuerMetadata const&) const CCF/build/CCF/src/node/jwt_key_auto_refresh.h:321:29 (logging+0x729494)
...
2025-11-07T14:48:11.8754071Z 
2025-11-07T14:48:11.8754204Z   Previous write of size 1 at 0x7ffff789a978 by thread T8:
2025-11-07T14:48:11.8754616Z     #0 std::ctype<char>::narrow(char, char) const /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/locale_facets.h:945:47 (logging+0x2002d3)
2025-11-07T14:48:11.8755036Z     #1 std::__detail::_Scanner<char>::_M_scan_normal() /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_scanner.tcc:100:51 (logging+0x2008ed)
2025-11-07T14:48:11.8755427Z     #2 std::__detail::_Scanner<char>::_M_advance() /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_scanner.tcc:79:2 (logging+0x1ffd7d)
2025-11-07T14:48:11.8756217Z     #3 std::__detail::_Compiler<std::__cxx11::regex_traits<char>>::_M_match_token(std::__detail::_ScannerBase::_TokenT) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_compiler.tcc:575:15 (logging+0x1fde1b)
2025-11-07T14:48:11.8756713Z     #4 std::__detail::_Compiler<std::__cxx11::regex_traits<char>>::_M_atom() /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_compiler.tcc:330:9 (logging+0x207456)
2025-11-07T14:48:11.8757173Z     #5 std::__detail::_Compiler<std::__cxx11::regex_traits<char>>::_M_term() /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_compiler.tcc:133:17 (logging+0x2067b3)
2025-11-07T14:48:11.8757669Z     #6 std::__detail::_Compiler<std::__cxx11::regex_traits<char>>::_M_alternative() /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_compiler.tcc:115:17 (logging+0x20636c)
2025-11-07T14:48:11.8758293Z     #7 std::__detail::_Compiler<std::__cxx11::regex_traits<char>>::_M_alternative() /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_compiler.tcc:118:10 (logging+0x20639f)
2025-11-07T14:48:11.8758785Z     #8 std::__detail::_Compiler<std::__cxx11::regex_traits<char>>::_M_disjunction() /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_compiler.tcc:91:13 (logging+0x1fdc3c)
2025-11-07T14:48:11.8759498Z     #9 std::__detail::_Compiler<std::__cxx11::regex_traits<char>>::_Compiler(char const*, char const*, std::locale const&, std::regex_constants::syntax_option_type) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex_compiler.tcc:76:13 (logging+0x1fd140)
2025-11-07T14:48:11.8760158Z     #10 std::__cxx11::basic_regex<char, std::__cxx11::regex_traits<char>>::_M_compile(char const*, char const*, std::regex_constants::syntax_option_type) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex.h:809:34 (logging+0x1fcd3f)
2025-11-07T14:48:11.8760777Z     #11 std::__cxx11::basic_regex<char, std::__cxx11::regex_traits<char>>::basic_regex(char const*, std::regex_constants::syntax_option_type) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/regex.h:473:9 (logging+0x1fc9c2)
2025-11-07T14:48:11.8761334Z     #12 http::parse_url_full(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) CCF/build/CCF/src/http/http_parser.h:150:16 (logging+0x655ba6)
2025-11-07T14:48:11.8762359Z     #13 ccf::JwtKeyAutoRefresh::refresh_jwt_keys()::'lambda'(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, ccf::JwtIssuerMetadata const&)::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, ccf::JwtIssuerMetadata const&) const CCF/build/CCF/src/node/jwt_key_auto_refresh.h:321:29 (logging+0x729494)
...
2025-11-07T14:48:11.9114416Z SUMMARY: ThreadSanitizer: data race CCF/build/CCF/src/http/http_parser.h:150:16 in http::parse_url_full(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)
2025-11-07T14:48:11.9115083Z ==================
2025-11-07T14:48:11.9115289Z ThreadSanitizer: reported 2 warnings
```

### PR DESCRIPTION
**Pull request by eddyashton**
Should resolve #7446.

See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77704 for discussion of the bug, and the workaround we crib.

### CODE REVIEW

File: src/host/run.cpp [hunk 1]
```diff
@@ -872,6 +872,25 @@ namespace ccf
     return std::nullopt;
   }
 
+  void apply_stdlib_workarounds()
```
Comment (achamayou) [inline src/host/run.cpp:875]:
```suggestion
  void apply_libstdcxx_workarounds()
```

is a little more accurate

Comment (eddyashton) [reply src/host/run.cpp:875]: I think if we find anything in libcxx warranting a similar workaround, it goes in this function too (appropriately guarded)? Of course if we found one in nlohmann::json or CLI11 I might _also_ want the workaround here.

I vote for leaving our warts unsatisfying, as this clearly is.

Comment (achamayou) [reply src/host/run.cpp:875]: Surely those wouldn't be here, or this would be renamed `apply_all_the_workarounds()`. Anyway that's fair enough, this can be stdlib workarounds with suitable ifdefs.

File: src/host/run.cpp [hunk 2]
```diff
@@ -872,6 +872,25 @@ namespace ccf
...
+  {
+    // A data race happens in the libstdc++ implementation of ctype::narrow.
+    // See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77704
+    // This workaround is from the mailing list - avoid unprotected lazy
+    // initialisation by eagerly initialising every value now.
+#if defined(__GLIBCXX__)
+    {
+      const std::ctype<char>& ct(
```
Comment (achamayou) [inline src/host/run.cpp]:
```suggestion
      const auto& ct(
```
