### PR TITLE
Smart wait for msg to arrive in channel test

### LINKED ISSUE #5853: channels_test is flaky in SNP builds
Failure observed in https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=79185&view=logs&jobId=4bdd83b0-b422-5e84-0058-fb00a4da194e&j=4bdd83b0-b422-5e84-0058-fb00a4da194e&t=01ab89b5-2bb2-5b36-1c41-59a63e14a55c

```
24: Test command: /CCF/build/channels_test
24: Environment variables: 
24:  TSAN_OPTIONS=suppressions=/CCF/tsan_env_suppressions
24:  ASAN_OPTIONS=alloc_dealloc_mismatch=0
24: Test timeout computed to be: 10000000
24: [doctest] doctest version is "2.4.11"
24: [doctest] run with "--help" for options
24: ===============================================================================
24: ../src/node/test/channels.cpp:1405:
24: TEST CASE:  Key rotation
24: 
24: ../src/node/test/channels.cpp:1562: FATAL ERROR: REQUIRE( received_by_2 == expected_received_by_2 ) is NOT correct!
24:   values: REQUIRE( {?} == {?} )
24: 
24: ===============================================================================
24: [doctest] test cases:   11 |   10 passed | 1 failed | 0 skipped
24: [doctest] assertions: 1517 | 1516 passed | 1 failed |
24: [doctest] Status: FAILURE!
24/57 Test #24: channels_test ....................***Failed    6.19 sec
```

### PR DESCRIPTION
**Pull request by maxtropets**
Closes #5853

- Was able to repro same sort of failure locally by playing around with `sleep`s.
- Changing pure sleep to a more robust waiting + additional checks for messages to arrive.
- In case it reproduces, we'll be able to distinguish corrupted messages from messages never sent.

### CODE REVIEW

File: src/node/test/channels.cpp [hunk 1]
```diff
@@ -1550,13 +1550,40 @@ TEST_CASE_FIXTURE(IORingbuffersFixture, "Key rotation")
     std::this_thread::sleep_for(std::chrono::milliseconds(20));
   }
 
-  // Assume this sleep is long enough for channel threads to fully catch up
-  std::this_thread::sleep_for(std::chrono::milliseconds(100));
+  // Wait for channel threads to fully catch up.
+  constexpr int wait_finish_attemtps = 100;
+  for (int attempt = 0; attempt < wait_finish_attemtps; attempt++)
```
Comment (eddyashton) [inline src/node/test/channels.cpp:1555]:
```suggestion
  constexpr int wait_finish_attempts = 100;
  for (int attempt = 0; attempt < wait_finish_attempts; attempt++)
```

**Review by achamayou — APPROVED** [review]

**Review by eddyashton — APPROVED** [review]
