### PR TITLE
Use a deterministic thread numbering scheme

### LINKED ISSUE #7165: Atempting to access task_id >= task_count
Error during `recovery_from_double_sealed_service` among others:
```
2025-08-06T17:47:02.225541Z        0   [info ] CCF/src/node/node_state.h:1000       | Starting to read public ledger
2025-08-06T17:47:02.227106Z        0   [info ] CCF/src/node/node_state.h:659        | Created recovery node n[998f3b640b04a672cfa85aa2c4318dd81a38465d96815d6ff025eb97f08198b2]
2025-08-06T17:47:02.278716Z        0   [info ] CCF/src/host/run.cpp:960             | Created new node
2025-08-06T17:47:02.278867Z        0   [info ] CCF/src/host/run.cpp:964             | Output self-signed node certificate to 0.pem
2025-08-06T17:47:02.278904Z        0   [info ] CCF/src/host/run.cpp:973             | Output service certificate to service_cert.pem
2025-08-06T17:47:02.278912Z        0   [info ] CCF/src/host/run.cpp:1001            | Starting enclave thread(s)
2025-08-06T17:47:02.278980Z        0   [info ] CCF/src/host/run.cpp:1009            | Entering event loop
2025-08-06T17:47:02.279047Z        0   [debug] CCF/src/host/load_monitor.h:84       | Host load: {"end_time_ms":1754502422279,"ringbuffer_messages":{"::consensus::ledger_get_range":{"bytes":17,"count":1}},"start_time_ms":1754502422102}
2025-08-06T17:47:02.279064Z        0   [debug] CCF/src/host/load_monitor.h:91       | Enclave load: {"end_time_ms":1754502422279,"ringbuffer_messages":{},"start_time_ms":1754502422102}
2025-08-06T17:47:02.279039Z        1   [info ] CCF/src/enclave/main.cpp:194         | Starting thread: 1
2025-08-06T17:47:02.279085Z        1   [info ] CCF/src/enclave/main.cpp:201         | All threads are ready!
2025-08-06T17:47:02.279029Z        0   [trace] CCF/src/host/ledger.h:508            | Read entries from 1 to 2 in ledger_1-2.committed [max size: 67106816]
2025-08-06T17:47:02.279131Z        1   [debug] CCF/src/enclave/enclave.h:443        | Running worker thread
2025-08-06T17:47:02.279361Z        1   [fail ] CCF/src/host/run.cpp:990             | Exception in ccf::run: Attempting to access task_id >= task_count, task_id:1, task_count:1
2025-08-06T17:47:02.279474Z        0   [trace] CCF/src/host/ledger.h:508            | Read entries from 3 to 16 in ledger_3-16.committed [max size: 67043199]
2025-08-06T17:47:02.279910Z        0   [trace] CCF/src/host/ledger.h:508            | Read entries from 17 to 19 in ledger_17-19.committed [max size: 67017042]
2025-08-06T17:47:02.280120Z        0   [trace] CCF/src/host/ledger.h:508            | Read entries from 20 to 21 in ledger_20-21.committed [max size: 67008029]
2025-08-06T17:47:02.280371Z        0   [trace] CCF/src/host/ledger.h:508            | Read entries from 22 to 43 in ledger_22-43.committed [max size: 67005664]
2025-08-06T17:47:02.280691Z        0   [trace] CCF/src/host/ledger.h:508            | Read entries from 44 to 64 in ledger_44-64.committed [max size: 66986783]
2025-08-06T17:47:02.281126Z        0   [trace] CCF/src/host/ledger.h:508            | Read entries from 65 to 84 in ledger_65-84.committed [max size: 66969893]
2025-08-06T17:47:02.281327Z        0   [trace] CCF/src/host/ledger.h:508            | Read entries from 85 to 100 in ledger_85-104.committed [max size: 66953368]
2025-08-06T17:47:02.386733Z        0   [debug] CCF/src/host/rpc_connections.h:183   | rpc start 2 on interface "primary_rpc_interface" as TCP
2025-08-06T17:47:02.387041Z        0   [trace] CCF/src/host/tcp.h:758               | Allocating 16384 bytes for TCP read (49152 of quota remaining)
2025-08-06T17:47:02.387096Z        0   [debug] CCF/src/host/rpc_connections.h:123   | rpc read 2: 517
```

`cmake -L ..`
```
-- CCF Devel Mode: ON
-- CCF version = ccf-7.0.0-dev1-27-ga5515de53
-- CCF release version = 7.0.0
-- CCF version suffix = dev1-27-ga5515de53
-- RPM package version: 7.0.0~dev1-27-ga5515de53
-- RPM package dependencies: openssl-devel >= 3.3.0, nghttp2-devel >= 1.40.0, cmake >= 3.30, build-essential >= 3.0, clang >= 18.1.2, ninja-build >= 1.11.1, libuv >= 1.34.2, curl >= 7.68.0, libcxxabi >= 18.1.2
-- Final RPM package name: ccf_devel_7.0.0~dev1-27-ga5515de53_x86_64.rpm
-- CMAKE_INSTALL_PREFIX is '/opt/ccf'
-- snmalloc: Using static TLS model
-- QuickJS prefix: /home/cjen1-msft/5.ccf/3rdparty/exported/quickjs version: 2024-01-13
-- OS_RELEASE = Microsoft Azure Linux
-- Configuring done (0.1s)
-- Generating done (0.1s)
-- Build files have been written to: /home/cjen1-msft/5.ccf/build
-- Cache values
BUILD_END_TO_END_TESTS:BOOL=ON
BUILD_TESTS:BOOL=ON
BUILD_UNIT_TESTS:BOOL=ON
CCF_DEVEL:BOOL=ON
CCF_RAFT_TRACING:BOOL=OFF
CLANG_TIDY:BOOL=OFF
CLIENT_PROTOCOLS_TEST:BOOL=OFF
CMAKE_BUILD_TYPE:STRING=Debug
CMAKE_INSTALL_PREFIX:PATH=/opt/ccf
COLORED_OUTPUT:BOOL=ON
COVERAGE:BOOL=OFF
CRYPTO_LIBRARY:FILEPATH=/usr/lib/libcrypto.so
DISTRIBUTE_PERF_TESTS:STRING=
FOUND_CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++
FOUND_CMAKE_C_COMPILER:FILEPATH=/usr/bin/clang
KV_STATE_RB:BOOL=OFF
LONG_TESTS:BOOL=OFF
PROFILE_TESTS:BOOL=OFF
QUICKJS_PREFIX:PATH=/home/cjen1-msft/5.ccf/3rdparty/exported/quickjs
SAN:BOOL=OFF
SHUFFLE_SUITE:BOOL=OFF
SNMALLOC_BENCHMARK_INDIVIDUAL_MITIGATIONS:BOOL=OFF
SNMALLOC_CHECK_LOADS:BOOL=OFF
SNMALLOC_CI_BUILD:BOOL=OFF
SNMALLOC_CLEANUP:STRING=PTHREAD_DESTRUCTORS
SNMALLOC_DEALLOC_BATCH_RING_ASSOC:STRING=
SNMALLOC_DEALLOC_BATCH_RING_SET_BITS:STRING=
SNMALLOC_ENABLE_DYNAMIC_LOADING:BOOL=OFF
SNMALLOC_ENABLE_FUZZING:BOOL=OFF
SNMALLOC_ENABLE_WAIT_ON_ADDRESS:BOOL=ON
SNMALLOC_HEADER_ONLY_LIBRARY:BOOL=OFF
SNMALLOC_IPO:BOOL=OFF
SNMALLOC_LINK_ICF:BOOL=ON
SNMALLOC_MIN_ALLOC_SIZE:STRING=
SNMALLOC_MIN_ALLOC_STEP_SIZE:STRING=
SNMALLOC_NO_REALLOCARR:BOOL=ON
SNMALLOC_NO_REALLOCARRAY:BOOL=ON
SNMALLOC_OPTIMISE_FOR_CURRENT_MACHINE:BOOL=OFF
SNMALLOC_PAGEID:BOOL=OFF
SNMALLOC_PAGESIZE:STRING=
SNMALLOC_QEMU_WORKAROUND:BOOL=OFF
SNMALLOC_RUST_SUPPORT:BOOL=OFF
SNMALLOC_SANITIZER:STRING=
SNMALLOC_STATIC_LIBRARY:BOOL=ON
SNMALLOC_STATIC_LIBRARY_PREFIX:STRING=sn_
SNMALLOC_TRACING:BOOL=OFF
SNMALLOC_USE_CXX17:BOOL=OFF
SNMALLOC_USE_SELF_VENDORED_STL:BOOL=OFF
TLS_LIBRARY:FILEPATH=/usr/lib/libssl.so
TSAN:BOOL=OFF
USE_LIBCXX:BOOL=OFF
USE_NULL_ENCRYPTOR:BOOL=OFF
USE_SNMALLOC:BOOL=ON
VERBOSE_LOGGING:BOOL=ON
WORKER_THREADS:STRING=0
```

Possibly a follow-on from #7152

### PR DESCRIPTION
**Pull request by cjen1-msft**
Closes #7165 

The issue was that a host side `ledger.h` thread logged between when the thread counters were reset and the first enclave thread was created giving it thread id 1 rather than 0, causing the enclave side task system to crash.

This PR instead explicitly passes a thread id into each enclave thread, which then updates the thread_local storage as soon as it starts to reflect this.

The result is that if we want to change the way the task system interacts with thread ids, at least for enclave threads, this will now be deterministic and relatively simple to update.

### CODE REVIEW

File: src/enclave/thread_local.cpp [hunk 1]
```diff
@@ -6,12 +6,22 @@ namespace ccf::threading
 {
   static std::atomic<ThreadID> next_thread_id = MAIN_THREAD_ID;
 
-  uint16_t get_current_thread_id()
+  uint16_t& get_current_thread_id_unsafe()
```
Comment (achamayou) [inline src/enclave/thread_local.cpp]:
```suggestion
  uint16_t& current_thread_id()
```

File: src/enclave/thread_local.cpp [hunk 2]
```diff
@@ -6,12 +6,22 @@ namespace ccf::threading
...
   {
     thread_local ThreadID this_thread_id = next_thread_id.fetch_add(1);
     return this_thread_id;
   }
 
+  uint16_t get_current_thread_id()
+  {
+    return get_current_thread_id_unsafe();
```
Comment (achamayou) [inline src/enclave/thread_local.cpp]:
```suggestion
    return current_thread_id();
```

File: src/enclave/thread_local.cpp [hunk 3]
```diff
@@ -6,12 +6,22 @@ namespace ccf::threading
...
+  }
+
+  void set_current_thread_id(ThreadID to)
+  {
+    get_current_thread_id_unsafe() = to;
```
Comment (achamayou) [inline src/enclave/thread_local.cpp]:
```suggestion
    current_thread_id() = to;
```
