### PR TITLE
PBFT - many things including fixes

### LINKED ISSUE #860: Primary not retransmitting forwarded requests
There is a corner case in PBFT where view changes will be triggered when there is no need for it. The scenario is (for a request with rid: `r`)

Notes:
- Primary (A) re-transmits requests when it receives status messages from other replicas
- A replica (B) that is a little bit behind (not a late joiner) will send out status messages

Bug explained:

- Replica (B) gets a request `r` and the related information it needs to execute and commit
- Replica (B) will execute for `r` at seqno `n`
- The primary (A) which is already further ahead will get (B)s status message and retransmit request `r`
- Replica (B) will re-receive request `r`, won't be able to add it to the "big request queue" causing it to be added to its `rqueue` which tracks requests and issues view changes if they haven't been executed
- Replica (B) forwards the request `r` to the primary and starts the view change timer
- The primary (A) will receive the request `r` but not via the client proxy, so the request `r` will not be broadcasted as is done usually to the other replicas
- The primary (A) will execute the request, send out pre-prepare with seqno `n'` to the other replicas, advance its last tentative execution seqno, and wait for prepares/commits from other replicas for seqno `n'`
- The other replicas will receive the pre-prepare, but they do not have the request `r` since it has not been broadcasted to them again, they will never be able to prepare/commit for this request
- The primary (A) can't make progress because it first needs to commit for request `r` at seqno `n'`
- No progress is being made while primary (A) is blocked so replica (B) and the others in time, will issue a view change

It is OK for now to execute requests again since we do not offer exactly once semantics and that should be left to the app, but if a request gets executed on the primary the other replicas _should_ be able to execute it too, so the request needs to be broadcasted.

### PR DESCRIPTION
**Pull request by ashamis**
Resolves #860
related to #459 & #690 

1. Ensure all ledgers are the same by writing the signatures for pp-1 on pp (still need to do verification)
2. Sign every pre-prepare (for receipts)
3. Do not mark stable every time we sign, this fixes many things........

### CODE REVIEW

**Comment by cimetrics** [comment]
prepare_9@[5455 aka 20200302.1](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=5455&view=results) vs master ewma over 14 builds from [5233](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=5233&view=results) to [5437](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=5437&view=results)
images

File: src/consensus/pbft/libbyz/Pre_prepare.cpp [hunk 1]
```diff
@@ -7,14 +7,19 @@
...
 #include "Request.h"
 #include "pbft_assert.h"
 
 Pre_prepare::Pre_prepare(
-  View v, Seqno s, Req_queue& reqs, size_t& requests_in_batch) :
+  View v,
+  Seqno s,
+  Prepared_cert* prepared_cert,
+  Req_queue& reqs,
+  size_t& requests_in_batch) :
```
Comment (olgavrou) [inline src/consensus/pbft/libbyz/Pre_prepare.cpp]: move prepared_cert to end and set it to nullptr by default

File: src/consensus/pbft/libbyz/Replica.cpp [hunk 2]
```diff
@@ -484,9 +484,13 @@ void Replica::playback_pre_prepare(ccf::Store::Tx& tx)
 
     global_commit(executable_pp.get());
 
-    if (executable_pp->is_signed() && f() > 0)
+    if (f() > 0 && (last_executed % checkpoint_interval == 0))
     {
-      mark_stable(last_executed, true);
+      Seqno stable_point = std::max(
```
Comment (olgavrou) [inline src/consensus/pbft/libbyz/Replica.cpp]: stable_point not used
