### PR TITLE
Switch BFT to hashed public key node ids

### LINKED ISSUE #1852: AFT: Support reconfiguration
This is the top level ticket for reconfiguration. This will be broken down into multiple tickets and PRs.

- [ ] Change the BFT node_id to be the same as in CFT. To do this we will need to keep a node_id -> ordered_id mapping and have a data structure that can allow us to deterministically decide which node is the primary in any given view within a configuration.
- [ ] Change BFT to use replica ids which have the same NodeIds that are derived from the public cert like CFT

### PR DESCRIPTION
**Pull request by wintersteiger**
Fixes #1852

### CODE REVIEW

File: src/node/rpc/node_call_types.h [hunk 1]
```diff
@@ -94,7 +94,7 @@ namespace ccf
     struct Out
     {
       NodeStatus node_status;
-      NodeId node_id; // Only used in BFT
+      std::optional<NodeId> node_id; // Only used in BFT
```
Comment (jumaffre) [inline src/node/rpc/node_call_types.h:97]:
```suggestion
      std::optional<NodeId> node_id;
```

File: src/node/rpc/node_frontend.h [hunk 2]
```diff
@@ -611,6 +598,8 @@ namespace ccf
             if (primary_id.has_value() && !consensus->view_change_in_progress())
             {
               out.primary_id = primary_id.value();
+              LOG_DEBUG_FMT(
```
Comment (jumaffre) [inline src/node/rpc/node_frontend.h:601]: Delete?

**Comment by wintersteiger** [comment]
> I believe the `values` tables can be removed altogether, without causing any issues of backwards compatibility either.

That's correct, but I might want to use it for the Byzantine identity work - I'll either move it to a new name or remove it altogether if I end up not needing it.
