### PR TITLE
Remove root from receipts

### LINKED ISSUE #2921: Remove root from receipts by default
Having the root in receipts is convenient for debugging, but counter-productive in terms of usability, since it makes it easier to implement incomplete/incorrect verification.

It should be off by default.

### PR DESCRIPTION
**Pull request by achamayou**
Fix #2921

### CODE REVIEW

**Review by wintersteiger — APPROVED** [review]
I totally agree, the root doesn't need to be in there.

File: include/ccf/receipt.h [hunk 1]
```diff
@@ -27,5 +27,6 @@ namespace ccf
   DECLARE_JSON_REQUIRED_FIELDS(Receipt::Element);
   DECLARE_JSON_OPTIONAL_FIELDS(Receipt::Element, left, right)
   DECLARE_JSON_TYPE(Receipt)
```
Comment (jumaffre) [inline include/ccf/receipt.h:29]:
```suggestion
  DECLARE_JSON_TYPE_WITH_OPTIONAL_FIELDS(Receipt)
```

**Review by jumaffre — APPROVED** [review]
