### PR TITLE
Use hash of certificate for user and member IDs

### LINKED ISSUE #1378: Re-evaluate the use of KV-driven incrementing IDs for users, members, nodes and proposals
Our incrementing IDs expose CCF users to dangerous mistakes in the presence of rollbacks.

We could remove these IDs entirely. In most places we can instead use the digest of the caller's cert, and the only case this doesn't work is Proposals for which we should be able to generate a UID (on the node, while processing `/gov/propose`).

### PR DESCRIPTION
**Pull request by jumaffre**
Fixes #1378 (part II)

We now use a hex-encoded string of the SHA-256 hash of the DER-encoded certificate (a.k.a [fingerprint](https://ldapwiki.com/wiki/Certificate%20Fingerprint#:~:text=The%20Certificate%20Fingerprint%20is%20the,entire%20certificate%20in%20DER%20form.)) for the member and user IDs. 

This has the following implication: the user and member certs and digests KV tables are gone and the `keyId` in signed HTTP requests is set to the Member/User ID. 

The Python infra still tracks members/users as `0`, `1`, etc. (`local_id`) but also knows their CCF IDs (`service_id`).

### CODE REVIEW

File: src/node/client_signatures.h [hunk 1]
```diff
@@ -54,6 +54,4 @@ namespace ccf
   };
   DECLARE_JSON_TYPE(SignedReq)
   DECLARE_JSON_REQUIRED_FIELDS(SignedReq, sig, req, request_body, md, key_id)
-  // this maps client-id to latest SignedReq
-  using ClientSignatures = kv::Map<CallerId, SignedReq>;
```
Comment (jumaffre) [inline src/node/client_signatures.h:58]: This was unused.

File: doc/schemas/gov_openapi.json [hunk 2]
```diff
@@ -66,6 +66,28 @@
...
+                "$ref": "#/components/schemas/Script"
+              }
+            ]
+          },
+          "maxItems": 2,
+          "minItems": 2,
+          "type": "array"
+        },
+        "type": "array"
+      },
```
Comment (eddyashton) [inline doc/schemas/gov_openapi.json:90]: I think it should be possible to convert this `std::map` to an object (since the keys are strings), but since we wrap them in another type `nlohmann::json` will produce an array of pairs, which at least we correctly describe here.

Comment (eddyashton) [reply doc/schemas/gov_openapi.json:90]: This is another "more of a comment than a suggestion", don't think there's any way around this with our current JSON abstractions.

File: src/node/certs.h [hunk 3]
```diff
@@ -1,12 +1,11 @@
 // Copyright (c) Microsoft Corporation. All rights reserved.
 // Licensed under the Apache 2.0 License.
 #pragma once
+
 #include "entities.h"
 
 namespace ccf
 {
-  using CertDERs = kv::Map<Cert, ObjectId>;
+  using CertDERs = kv::Map<Cert, CallerId>;
```
Comment (eddyashton) [inline src/node/certs.h:9]: I think this table can also be removed, since we can also recompute this `Cert -> CallerId` when needed?

Comment (jumaffre) [reply src/node/certs.h:9]: Ah! Very good point.

File: tests/e2e_logging.py [hunk 4]
```diff
@@ -241,15 +244,15 @@ def require_new_response(r):
                 require_new_response(r)
 
             LOG.info("Authenticate as a member, via TLS cert")
-            with primary.client("member0") as c:
+            with primary.client(f"member{member.local_id}") as c:
```
Comment (eddyashton) [inline tests/e2e_logging.py:247]: Since this construction is so common, should we instead just store this full string as `local_id`? ie - if we never use the `local_id` of `0` in isolation, its only ever to construct `"member0"` or `"user0"`, then we may as well store that string directly (with the bonus that when we've generated a key for `"alice"`, this works, and we don't need to copy her keys to `useralice.pem` and `memberalice.pem`).

File: tests/start_network.py [hunk 5]
```diff
@@ -55,6 +55,7 @@ def run(args):
             network.start_and_join(args)
 
         primary, backups = network.find_nodes()
+        max_len = len(str(len(backups)))
```
Comment (eddyashton) [inline tests/start_network.py:58]:
```suggestion
        max_len = max(len(str(backup.local_node_id)) for backup in backups)
```

Else this breaks when we have 3 nodes left, but they're 9, 10, and 11 (or 1, 100, and 100000000).

File: src/node/certs.h (hunk 3 above)
Comment (jumaffre) [reply src/node/certs.h:9]: Done now. Let's see if hashing the DER certificate on every request has any impact on performance.

File: src/node/node_id.h [hunk 6]
```diff
@@ -105,32 +58,25 @@ namespace ccf
...
     }
   };
-
 }
 
-// Only display the first node_id_truncation_max_char_count character when
-// printing the node id to the node's log
+// Node ids are printed in many places (e.g. consensus) so only display the
+// first node_id_truncation_max_char_count characters when printing it to the
+// node's log (e.g. using the LOG_..._FMT() macros)
```
[the remark this answers is not in the document]
Comment (jumaffre) [reply src/node/node_id.h:79]: Good point. My first though was that we don't print the member/user IDs very often so the full hash would be OK then. But I'd rather go with a unified way of dealing with/printing entities in the logs, so I'll merge the two.

File: doc/schemas/gov_openapi.json (hunk 2 above)
Comment (jumaffre) [reply doc/schemas/gov_openapi.json:79]: Good spot. I didn't pay attention to this as we already had something similar when `MemberId`s were `uint64_t` (see `uint64_to_Script` on left-hand side of diff). Do you think there's a quick fix for this?

Comment (eddyashton) [reply doc/schemas/gov_openapi.json:79]: I don't think there's a quick fix, it should be possible with some explicit template instantiations but not worth investigating this now. Can you just check that this array-of-pairs is actually what's produced when we convert one of these maps to JSON? I notice that the nlohmann docs say any type "whose keys can construct an std::string" will convert to a JSON object, so its possible that your `operator std::string` on `EntityID` actually produces an object in the serialisation (in which case this auto-generated schema is wrong...).

File: src/node/entity_id.h [hunk 7]
```diff
@@ -0,0 +1,167 @@
...
+
+    auto& value() const
+    {
+      return id;
+    }
+
+    auto data() const
+    {
+      return id.data();
+    }
```
Comment (eddyashton) [inline src/node/entity_id.h:69]:
```suggestion
    Value& value()
    {
      return id;
    }

    const Value& value() const
    {
      return id;
    }

    char const* data() const
    {
      return id.data();
    }
```

It wasn't obvious to me that `auto& foo() const` was returning a `const Foo&` (rather than the dangerously broken `Foo&`-from-a-const-method), so I think we should spell this ourselves in the return types. And if we intend to use these for all accesses, `id` should be `protected`.

File: CHANGELOG.md [hunk 8]
```diff
@@ -10,7 +10,13 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 ### Changed
 
 - `x-ccf-tx-view` and `x-ccf-tx-seqno` response headers have been removed, and replaced with `x-ms-ccf-transaction-id`. This includes both original fields, separated by a single `.`. Historical queries using `ccf::historical::adapter` should also pass a single combined `x-ms-ccf-transaction-id` header (#2257).
-- Node unique identifier is the hex-encoded string of the SHA-256 digest of the node's identity public key, which is also used as the node's quote report data (#2241).
+- Node unique identifier is the hex-encoded string of the SHA-256 digest of the node's DER-encoded identity public key, which is also used as the node's quote report data (#2241).
+- Members and users unique identifier is the hex-encoded string of the SHA-256 digest of their DER-encoded identity certificate (i.e. fingerprint), which has to be specified as the `keyId` field for signed HTTP requests (#2279).
+
+### Removed
+
+- `/caller_id` endpoint. Members and users can compute their unique identifier without interacting with CCF (#2279).
```
Comment (achamayou) [inline CHANGELOG.md:18]:
```suggestion
- `/caller_id` endpoint. Members and users can now compute their unique identifier without interacting with CCF (#2279).
```

File: doc/governance/adding_member.rst [hunk 9]
```diff
@@ -30,6 +30,13 @@ Members that are registered in CCF `with` a public encryption key are recovery m
 
 The member’s identity and encryption private keys (e.g. ``member_name_privk.pem`` and ``member_name_enc_privk.pem``) should be stored on a trusted device (e.g. HSM) while the certificate (e.g. ``member_name_cert.pem``) and public encryption key (e.g. ``member_name_enc_pubk.pem``) should be registered in CCF by members.
 
+The CCF unique member identity is the hex-encoded string of the SHA-256 hash of the DER-encoded certificate, and can be computed without interacting with CCF:
```
Comment (achamayou) [inline doc/governance/adding_member.rst:33]:
```suggestion
The CCF unique member identity is the hex-encoded string of the SHA-256 hash of the DER-encoded certificate, and can be computed from the certificate alone, without interacting with CCF:
```

File: src/node/certs.h (hunk 3 above)
Comment (achamayou) [reply src/node/certs.h:9]: In the unlikely event that it does, we can always memoise it like we do for verifiers.

File: src/node/entity_id.h [hunk 10]
```diff
@@ -0,0 +1,167 @@
...
+  template <typename ParseContext>
+  auto parse(ParseContext& ctx)
+  {
+    return ctx.begin();
+  }
+
+  template <typename FormatContext>
+  auto format(const ccf::EntityId& entity_id, FormatContext& ctx)
+    -> decltype(ctx.out())
+  {
```
Comment (achamayou) [inline src/node/entity_id.h:159]: Why are we systematically truncating those in format?

File: src/node/certs.h (hunk 3 above)
Comment (jumaffre) [reply src/node/certs.h:9]: As per https://github.com/microsoft/CCF/pull/2279#issuecomment-792863287, these changes don't impact performance 👍

File: doc/schemas/gov_openapi.json (hunk 2 above)
Comment (jumaffre) [reply doc/schemas/gov_openapi.json:79]: As discussed, because of the `operator std::string()`, this serialised the map as an object. I've removed the operator and used `.value()` instead so that the schema is in line with what the serialisation code actually does.

File: src/node/entity_id.h (hunk 10 above)
Comment (jumaffre) [reply src/node/entity_id.h]: I've removed the custom formatting and added an explicit `trim()` member which is called from `raft.h` when the node ID needs to be printed (only on "sunny-day" messages).

**Review by eddyashton — APPROVED** [review]
