### PR TITLE
No logging induced ctrl flow

### LINKED ISSUE #782: Due to logging macro overloading, exception handling is incorrect in enclaves
**Description**
For non-enclave builds, logger.h overloads the logging functionality by throwing exceptions when LOG_FATAL_FMT events are logged. With enclave builds (#ifdef INSIDE_ENCLAVE), logger.h outputs the message, but does not throw an exception.  Code that is written with the expectation that LOG_FATAL_FMT will throw an exception, will not function correctly in the enclave. For example:

```
  void KeyAesGcm::encrypt(
...
  {
    int rc = mbedtls_gcm_crypt_and_tag(
      reinterpret_cast<mbedtls_gcm_context*>(ctx),
      MBEDTLS_GCM_ENCRYPT,
...
      tag);
    if (rc != 0)
    {
      LOG_FATAL_FMT(tls::error_string(rc));
    }
  }
```

With the current implementation, the host will log the event for the enclave, resulting in a thrown exception -- in the host. But the host is untrusted, and it could ignore fatal errors from the enclave, perhaps leaving the enclave in a vulnerable state if it wishes. In effect, the enclave is delegating its some of its control flow to the untrusted host.

**To Reproduce**
Log fatal events in the enclave, while ignoring them in the host.

**Expected behavior**
Control flow should not be affected by logging. My recommendation is to remove the embedded exception logic from the logging macro, and have functions explicitly and separately control the flow.

This is somewhat related to #777.

### PR DESCRIPTION
**Pull request by achamayou**
fix #782

### CODE REVIEW

**Comment by cimetrics** [comment]
no_logging_induced_ctrl_flow@[4804 aka 20200211.25](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=4804&view=results) vs master ewma over 30 builds from [4446](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=4446&view=results) to [4794](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=4794&view=results)
images

File: src/node/rpc/frontend.h [hunk 1]
```diff
@@ -589,7 +589,7 @@ namespace ccf
           // If serialising the committed transaction fails, there is no way to
           // recover safely (https://github.com/microsoft/CCF/issues/338).
           // Better to abort.
-          LOG_FATAL_FMT(e.what());
+          throw;
```
Comment (eddyashton) [inline src/node/rpc/frontend.h]: I had a comment here but it seems GitHub lost it?

Removing the macro means we remove the distinction between errors we know are recoverable (`throw std::logic_error`) and errors we think are really fatal ("I'd like to `abort` but I'll at least try to tell you why, and where"). In most of these instances that looks fine (we may be able to catch these safely, and in general they'll kill the node but in the same way as our other asserts).

I'm not sure about this instance though - if we get here, our kv is half-modified and we really do want to kill this node ASAP? I guess the threat is that another thread responds from the corrupt kv, and we can't reliably intercept that, so maybe this is fine. Thinking out loud.

Comment (achamayou) [reply src/node/rpc/frontend.h]: I don't think we do, because we throw the same exception either way. If the logging code has abort()ed, I would have agreed, but as it stands, I think it's really equivalent.

In this situation, we've committed a Tx, and we can't serialise it, there is no way out, so it is simpler to die than to confuse the other nodes?

File: src/host/tcp.h [hunk 2]
```diff
@@ -126,8 +126,8 @@ namespace asynchost
 
         default:
         {
-          LOG_FATAL_FMT("Unexpected status during reconnect: {}", status);
-          abort();
+          throw std::logic_error(
```
Comment (olgavrou) [inline src/host/tcp.h]: we don't want to abort here anymore?

File: src/node/rpc/frontend.h (hunk 1 above)
Comment (eddyashton) [reply src/node/rpc/frontend.h]: Agreed.

File: src/host/tcp.h (hunk 2 above)
Comment (achamayou) [reply src/host/tcp.h]: Uncaught exceptions also abort.

**Comment by ashamis** [comment]
should LOG_FATAL_FMT & LOG_FATAL be removed from Logger.h

**Comment by achamayou** [comment]
@ashamis we can keep it as a level I think, it just shouldn't throw.
