### PR TITLE
Revisit CCF crypto interfaces (mostly RSA/EC keys)

### LINKED ISSUE #6673: Fix RSAPublicKey hierarchy and hidden virtual functions
List of problems to solve while refactoring the interface for **signature verification**
* `RSAPublicKey` and `RSAKeyPair` both **define** `verify(signature_args..., md_type, salt_length)`, is it even legit?..
* `RSAKeyPair_OpenSSL` **implements** `verify(signature_args..., md_type, salt_length)`
* `PublicKey_OpenSSL` **implements** `verify(signature_args..., md_type, hash_bytes&)`. Here's why JWT authentication uses the wrong verification impl (check comment).
* `salt_length` is `size_t`, therefore it's not possible to pass options like `RSA_PSS_SALTLEN_AUTO == -2` or other predefined constants. Not sure what's the best way to do it in the interface, it's TBD how different paddings and salt work as per documentation first, but this has to be fixed.

### PR DESCRIPTION
**Pull request by maxtropets**
Resolves #6673 

- [x] Break RSA->EC inheritance
- [x] Rename `PublicKey -> ECPublicKey`, `KeyPair -> ECKeyPair`, etc
- [x] No more common public key, `ccf::crypto::KeyVariant` provided for explicit handing of different key types

✅ Long Test passed
☑️ AB perf: no regression

Mainly involved changes in RSA, other survived with no functional changes, the interface surface remains the same (except naming).

This's how it looks for RSA (and others, with probably extra non-exported files for historical reasons)

```
    ccf::crypto::RSAPublicKey          ccf::crypto::RSAKeyPair
               |                                  |
               |                                  |
               v                                  |
    RSAPublicKey_OpenSSL                          |
               |                                  |
               |                                  v
               └─────────────────────→  RSAKeyPair_OpenSSL
                                         (private_openssl)
```

### CODE REVIEW

File: src/crypto/certs.h [hunk 1]
```diff
@@ -23,7 +23,7 @@ namespace ccf::crypto
   }
 
   static Pem create_self_signed_cert(
-    const KeyPairPtr& key_pair,
+    const ECKeyPairPtr& key_pair,
```
Comment (eddyashton) [inline src/crypto/certs.h:26]: I'm surprised this isn't the `KeyVariant` - do we not allow RSA keys to be used for service/node identities, which would presumably go through these paths?

File: src/endpoints/authentication/jwt_auth.cpp [hunk 2]
```diff
@@ -89,10 +88,11 @@ namespace ccf
...
 
     using DER = std::vector<uint8_t>;
-    using KeyVariant =
-      std::variant<ccf::crypto::RSAPublicKeyPtr, ccf::crypto::PublicKeyPtr>;
     ccf::pal::Mutex keys_lock;
-    LRU<DER, KeyVariant> keys;
+
+    using ECPublicKey = ccf::crypto::
+      KeyVariant<ccf::crypto::RSAPublicKeyPtr, ccf::crypto::ECPublicKeyPtr>;
+    LRU<DER, ECPublicKey> keys;
```
Comment (eddyashton) [inline src/endpoints/authentication/jwt_auth.cpp]:
```suggestion
    using VariantPublicKey = ccf::crypto::
      KeyVariant<ccf::crypto::RSAPublicKeyPtr, ccf::crypto::ECPublicKeyPtr>;
    LRU<DER, VariantPublicKey> keys;
```

File: src/endpoints/authentication/jwt_auth.cpp [hunk 3]
```diff
@@ -114,32 +114,32 @@ namespace ccf
         }
         catch (const std::exception&)
         {
-          it = keys.insert(der, ccf::crypto::make_public_key(der));
+          it = keys.insert(der, ccf::crypto::make_ec_public_key(der));
         }
       }
 
       const auto& key = it->second;
       if (std::holds_alternative<ccf::crypto::RSAPublicKeyPtr>(key))
```
Comment (eddyashton) [inline src/endpoints/authentication/jwt_auth.cpp:123]: Slightly paranoid, but can we make sure this is exhaustive, and checks every possible value in the alternative (with a compile time error if one is missing)? You can do this with `std::visit` and `if constexpr` and `static_assert(nonstd::dependent_false`, and probably simpler ways too. It looks like we'd currently fall through to a `DEBUG` level `Key not found for der` error, which sounds wrong.

File: include/ccf/crypto/key_variant.h [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+#include "ccf/crypto/rsa_public_key.h"
+
+#include <variant>
+
+namespace ccf::crypto
+{
+  using InvalidKeyPtr = size_t*;
+
+  template <typename... Ts>
+  using KeyVariant = std::variant<Ts..., InvalidKeyPtr>;
```
Comment (eddyashton) [inline include/ccf/crypto/key_variant.h]: I'm missing something here. Appears that all users are `KeyVariant<RSAPublicKeyPtr, ECPublicKeyPtr>`, so why is this a template rather than directly defining `KeyVariant = std::variant<RSAPublicKeyPtr, ECPublicKeyPtr>`? And what does the `InvalidKeyPtr` get us?

Comment (maxtropets) [reply include/ccf/crypto/key_variant.h]: >So why is this a template rather than directly defining 

It's a public header, users may choose more/different options, like `EdDSAPublicKeyPtr`

Comment (maxtropets) [reply include/ccf/crypto/key_variant.h]: > And what does the InvalidKeyPtr get us?

A possibility to default-initialise the variant, with `nullptr` in particular.

File: src/crypto/certs.h (hunk 1 above)
Comment (maxtropets) [reply src/crypto/certs.h:26]: Good point, I somehow missed that you could've use it as an RSA key.

I'll need to populate that back to RSA impl

Comment (maxtropets) [reply src/crypto/certs.h:26]: As discussed, we shall not let that happen for RSA keys, so I won't resurrect that.

I'll update the changelog however, to make that clear.

File: src/endpoints/authentication/jwt_auth.cpp (hunk 3 above)
Comment (maxtropets) [reply src/endpoints/authentication/jwt_auth.cpp:123]: Good point, but I won't do it this PR, as it's not introducing this behaviour.

Also, it won't really happen, because this will throw earlier if can't create either key.

File: include/ccf/crypto/key_variant.h (hunk 4 above)
Comment (achamayou) [reply include/ccf/crypto/key_variant.h]: Do we ever want a default-initialised variant? I also wonder if this can be simplified.

File: include/ccf/crypto/rsa_public_key.h [hunk 5]
```diff
@@ -12,27 +12,15 @@
 
 namespace ccf::crypto
 {
+  enum class RSAPadding
```
Comment (achamayou) [inline include/ccf/crypto/rsa_public_key.h]:
```suggestion
  enum class RSAPadding : uint8_t
```

File: src/crypto/openssl/rsa_public_key.cpp [hunk 6]
```diff
@@ -26,20 +63,22 @@ namespace ccf::crypto
...
+      cleanup_pkey(&key);
       throw std::logic_error("invalid RSA key");
     }
   }
 
   RSAPublicKey_OpenSSL::RSAPublicKey_OpenSSL(std::span<const uint8_t> der)
   {
     const unsigned char* pp = der.data();
-    key = EVP_PKEY_new();
+    key = EVP_PKEY_new(); // NOLINT(cppcoreguidelines-prefer-member-initializer)
```
Comment (achamayou) [inline src/crypto/openssl/rsa_public_key.cpp:74]: Why not a member initializer? That would save the two manual cleanups, wouldn't it?

File: src/crypto/openssl/rsa_public_key.cpp [hunk 7]
```diff
@@ -177,39 +204,45 @@ namespace ccf::crypto
...
+    if (ossl_padding == rsa_padding_openssl.end())
+    {
+      throw std::logic_error("unsupported RSA padding");
+    }
+
     Unique_EVP_PKEY_CTX pctx(key);
     CHECK1(EVP_PKEY_verify_init(pctx));
-    CHECK1(EVP_PKEY_CTX_set_rsa_padding(pctx, RSA_PKCS1_PADDING));
+    CHECK1(EVP_PKEY_CTX_set_rsa_padding(pctx, ossl_padding->second));
+    if (ossl_padding->first == RSAPadding::PKCS_PSS)
```
Comment (achamayou) [inline src/crypto/openssl/rsa_public_key.cpp:239]: Is this adding support for PKCS_PSS?

File: src/crypto/openssl/rsa_public_key.cpp [hunk 8]
```diff
@@ -221,23 +254,70 @@ namespace ccf::crypto
...
+    return r;
+  }
+
+  RSAPublicKeyPtr make_rsa_public_key(const uint8_t* data, size_t size)
+  {
+    static constexpr auto PEM_BEGIN = "-----BEGIN";
+    static constexpr auto PEM_BEGIN_LEN =
+      std::char_traits<char>::length(PEM_BEGIN);
+
+    if (
```
Comment (achamayou) [inline src/crypto/openssl/rsa_public_key.cpp:296]: Is this new or for compatibility?

File: src/crypto/openssl/rsa_public_key.cpp (hunk 6 above)
Comment (maxtropets) [reply src/crypto/openssl/rsa_public_key.cpp:74]: This is a member of a PublicKey, and we fully intialize it in the KeyPair (PrivateKey).

That's how it was before, I decided to keep it this way, as I didn't find anything much better.

File: src/crypto/openssl/rsa_public_key.cpp (hunk 7 above)
Comment (maxtropets) [reply src/crypto/openssl/rsa_public_key.cpp:239]: No, this only keeps the existing support, for **verifying** only (needed by JWT).

File: include/ccf/crypto/key_variant.h (hunk 4 above)
Comment (maxtropets) [reply include/ccf/crypto/key_variant.h]: Because we may keep the key members uninitialised, they can be simply nothing, but IDK, honestly. I thought it does no harm to have it.

File: src/crypto/openssl/rsa_public_key.cpp (hunk 8 above)
Comment (maxtropets) [reply src/crypto/openssl/rsa_public_key.cpp:296]: Been here before, just shuffling.

Comment (maxtropets) [reply src/crypto/openssl/rsa_public_key.cpp:296]: I refrained from making some cleaning in this PR in the non-interace code, because it's too big, I'll probably make follow-ups though, with some implementation polishing.

File: include/ccf/crypto/verifier.h [hunk 9]
```diff
@@ -14,7 +14,7 @@ namespace ccf::crypto
   class Verifier
   {
   protected:
-    std::shared_ptr<PublicKey> public_key;
+    KeyVariant<RSAPublicKeyPtr, ECPublicKeyPtr> public_key{nullptr};
 
   public:
     Verifier() : public_key(nullptr) {}
```
Comment (eddyashton) [inline include/ccf/crypto/verifier.h]:
```suggestion
    std::variant<RSAPublicKeyPtr, ECPublicKeyPtr> public_key;

  public:
    Verifier() = default;
```

I don't think we need to define a `KeyVariant` wrapper type, since its only used in 2 places, neither public, and has unclear semantics (with the additional `InvalidKeyPtr` type). This and `jwt_auth.cpp` can directly use a `std::variant<RSAPublicKeyPtr, ECPublicKeyPtr>`, and no other code should need to change.

Comment (achamayou) [reply include/ccf/crypto/verifier.h]: We could have an ECRSAKeyVariant, but I agree that an unspecified KeyVariant that we might be tempted to extend doesn't seem useful. If it gets picked up, extension will break all usage unnecessarily.

File: src/crypto/openssl/rsa_public_key.cpp (hunk 6 above)
Comment (achamayou) [reply src/crypto/openssl/rsa_public_key.cpp:74]: ok

File: include/ccf/crypto/verifier.h (hunk 9 above)
Comment (maxtropets) [reply include/ccf/crypto/verifier.h]: Removed

File: include/ccf/crypto/key_variant.h (hunk 4 above)
Comment (maxtropets) [reply include/ccf/crypto/key_variant.h]: Removed

**Review by achamayou — APPROVED** [review]
