### PR TITLE
Fix VirtualCall clang tidy exception, and categorise list

### LINKED ISSUE #7120: Move all `make_endpoint()` calls to `init_handlers()` in samples.
See https://github.com/microsoft/CCF/pull/7117#discussion_r2213003940

### PR DESCRIPTION
**Pull request by achamayou**
Follow up to #7117. Closes #7120.

### CODE REVIEW

File: src/indexing/strategies/seqnos_by_key_bucketed.cpp [hunk 1]
```diff
@@ -258,6 +258,7 @@ namespace ccf::indexing::strategies
                 // This class previously wrote a bucket to disk which is no
                 // longer available or corrupted. Reset the watermark of what
                 // has been indexed, to re-index and rewrite those files.
+                // NOLINTNEXTLINE(clang-analyzer-deadcode.DeadStores)
```
Comment (maxtropets) [inline src/indexing/strategies/seqnos_by_key_bucketed.cpp]: Could you justify? Seem it's a local variable set before return, and not used.

Comment (maxtropets) [reply src/indexing/strategies/seqnos_by_key_bucketed.cpp]: Also, return + break a few lines down look bizarre, but NVM

**Review by maxtropets — APPROVED** [review]

File: src/indexing/strategies/seqnos_by_key_bucketed.cpp (hunk 1 above)
Comment (achamayou) [reply src/indexing/strategies/seqnos_by_key_bucketed.cpp]: I suspect this is set for clarity/ease of debugging, @eddyashton to confirm. I am happy to drop it though if we don't think it helps, I don't mind.

wrt to the return/break, I am fairly sure this is to avoid another warning, but we can test if the current tooling is smarter.

Comment (eddyashton) [reply src/indexing/strategies/seqnos_by_key_bucketed.cpp]: I'm not critically attached to either. I think they originally made sense as safeguards against future refactoring (if you don't return here, then `complete==false;` takes you closer to the correct paths later; if you remove the `return`, don't forget you're inside a `case:` block). But we should probably rely on the tooling (like clang-tidy) and test case coverage now, so I'm fine for this assignment to be removed rather than adding a suppression.

File: .clang-tidy [hunk 2]
```diff
@@ -2,52 +2,50 @@
...
   -performance-no-int-to-ptr,
-  -clang-analyzer-optin.cplusplus.VirtualCall,
-  -cppcoreguidelines-rvalue-reference-param-not-moved
+  portability-*,
+  readability-*,
+  -readability-function-cognitive-complexity,
+  -readability-identifier-length,
+  -readability-avoid-nested-conditional-operator,
+  -readability-convert-member-functions-to-static,
+  -readability-use-anyofallof
```
Comment (eddyashton) [inline .clang-tidy:48]: There are lots of changes to the options here. Is this just sorting? Or are there semantic changes as well?

Comment (achamayou) [reply .clang-tidy:48]: It's just sorting.

File: src/indexing/strategies/seqnos_by_key_bucketed.cpp (hunk 1 above)
Comment (achamayou) [reply src/indexing/strategies/seqnos_by_key_bucketed.cpp]: Everything can go.
