### PR TITLE
Make collateral fetching retries configurable, and shut down when they are exhausted

### LINKED ISSUE #6465: First node for CCF cluster failed to come up in CACI
Hit this issue on CACI where the start node itself has not come up. Looking at the container logs I see:
`[fail ] node/quote_endorsements_client.h:136 | Giving up retrying fetching attestation endorsements from 10.92.0.12 after 3 attempts`

Filing the bug to track this issue.

### PR DESCRIPTION
**Pull request by achamayou**
Closes #6465

In configuration, `attestation.snp_endorsements_servers` can specify a `max_retries_count`. If the count has been exhausted without success for all configured servers, the node will shut down (#6478).

### CODE REVIEW

File: include/ccf/pal/attestation.h [hunk 1]
```diff
@@ -442,6 +442,19 @@ namespace ccf::pal
...
+
+  class AttestationCollateralFetchingTimeout : public std::exception
+  {
+  private:
+    std::string msg;
+
+  public:
+    AttestationCollateralFetchingTimeout(const std::string& msg_) : msg(msg_) {}
+
+    virtual const char* what() const throw()
```
Comment (maxtropets) [inline include/ccf/pal/attestation.h:455]:
```suggestion
    virtual const char* what() const noexcept
```

`throw()` is deprecated since C++17 and removed in C++20

**Review by maxtropets — APPROVED** [review]

File: include/ccf/pal/attestation.h (hunk 1 above)
Comment (achamayou) [reply include/ccf/pal/attestation.h:455]: Will fix every occurrence in a separate PR, this is consistent with existing usage.
