### PR TITLE
Raft committable suffix: efficient backtracking to find safe matching index

### LINKED ISSUE #2803: Incorrect suffix retained after election
The changes in #2801 have hit a Raft bug very similar to the one described in #2189 (and believed fixed in #2192). Specifically, that fix to "accept a rollback instruction from the new primary" is not reached if the node rejects the AppendEntries early in processing, for instance because it is not contiguous with its current ledger or it disagrees on the previous term. The former is legitimate, but the latter is not and can lead to permanent commit lock.

From spelunking in some logs, one incorrect flow was observed:
- Node 0 is briefly primary in term 8
- Node 0 produces a signature at 8.25, but doesn't manage to tell anyone about it
- Node 1 becomes primary in term 9
- Node 1 produces a transaction at 9.25, and proceeds to 9.26
- Node 1 sends AppendEntries to 0 containing 9.25 -> 9.26
- Node 0 sees an AppendEntries in term 9, and dutifully rolls back to its `last_committable` (setting `is_new_follower`, but hoping that its 25 is still useful)
- Node 0 processes the AppendEntries and says "no, that looks like junk to me"

0's logs show it rejecting an AppendEntries it should have accepted:
```
24:49.243 |00| Received append entries: 9.25 to 9.26 (from 1=bf9b in term 9) (raft.h:1350)
24:49.243 |00| Previous term for 25 should be 8 (raft.h:1439)
24:49.243 |00| Recv append entries to n[0=92bf] from n[1=bf9b] but our log at 25 has the wrong previous term (ours: 8, theirs: 9) (raft.h:1461)
24:49.243 |00| Send append entries response from 0=92bf to 1=bf9b for index 25: 1 (raft.h:2084)
```

This is a more general problem than that precise flow. For instance the locked node could have been any follower of 0 in term 8. Its not critical that they produced the signature, just that it is the final entry in their log and disagrees with an AppendEntries they should be obeying.

I'm currently considering 2 possible fixes:
- Obey an AppendEntries rollback in more circumstances. This should just involve moving a block of code earlier in the `recv_append_entries` function. However reasoning about exactly where it should go is tricky, as we want to (if possible) keep the current behaviour that it is robust to replay (we only do this immediately after becoming follower, if we did it blindly then a malicious host could trivially cause us to repeatedly roll back to this point and lose state).
- Change what we report to the primary when rejecting AppendEntries. The Raft paper says we should return the first TxID we disagree with, so the host knows where the next AppendEntries should start. We actually send our latest index (which may be junk that we're holding optimistically while in `is_new_follower`), and the primary treats that as the matching index. Sending the last we agree with should be equivalent to the first we disagree with, and may be a small fix that fixes everything.

I still don't know why this has arisen from #2801, and will look for a simpler repo for a standalone fix.

### PR DESCRIPTION
**Pull request by eddyashton**
Resolves #2803.

Follow up to #2835, using a more accurate and crucially persistence-retaining method for finding the last index where 2 divergent logs disagree.

As described in #2803; sending an early index is potentially unsafe as it may cause a log to roll back too far and lose state it is responsible for committing (though later than its local knowledge of `commit_idx`). Discarding a matching prefix is non-trivial, since we do not know the term and index of an item inside an AppendEntries (which is what we wish to use for equality checking) until after we have deserialised it, and our deserialisation and application are closely coupled.

This PR includes 2 new unit tests (in `committable_suffix.cpp`) which demonstrate the risk here, and failed with the previous implementation. The first involves 5 nodes, where 2 are responsible for persisting a dead primary's committed suffix, but in resolving disagreement about their local attempts at extending the log, one was rolling back too far. The other is a 3-node network where 2 nodes build long suffixes of alternating terms, without advancing commit, and confirms both that the eventual stable primary is able to bring the other back in-sync to advance commit, and that the back-tracking logic to discover their matching index is efficient (bounded by the number of terms in the worst case, rather than the number of log entries).

This includes a refactoring of `raft/test/main.cpp`, to put these test cases in a separate file and move some of the shared test setup to `test_common.h`.

The interesting behaviour changes are in `raft.h` and `aft/impl/state.h`, centered on `find_highest_possible_match`. This is used both when constructing a NACK, and updating `matching_idx` to respond to that NACK, to backtrack through the best-possible estimates of matching indices until eventually the backup receives an AppendEntries with no conflicts, following immediately from their last matching index.

### CODE REVIEW

File: src/consensus/aft/raft.h [hunk 1]
```diff
@@ -2424,33 +2457,47 @@ namespace aft
       {
         // Stale response, discard if success.
         // Otherwise reset sent_idx and try again.
-        LOG_DEBUG_FMT(
-          "Recv append entries response to {} from {}: stale term ({} != {})",
-          state->my_node_id,
-          from,
-          r.term,
-          state->current_view);
+        // NB: In NACKs this may contain the TxID of an estimated matching index
```
Comment (achamayou) [inline src/consensus/aft/raft.h:2460]:
```suggestion
        // NB: In NACKs this response may contain the TxID of an estimated matching index
```

File: src/consensus/aft/raft.h [hunk 2]
```diff
@@ -2424,33 +2457,47 @@ namespace aft
...
+        // in the log, rather than the current term, so it is correct for it to
+        // be stale in this case.
```
Comment (achamayou) [inline src/consensus/aft/raft.h:2462]:
```suggestion
        // be older in this case.
```

File: src/consensus/aft/raft.h [hunk 3]
```diff
@@ -2424,33 +2457,47 @@ namespace aft
...
+            state->my_node_id,
+            from,
+            r.term,
+            state->current_view);
           return;
         }
       }
       else if (r.last_log_idx < node->second.match_idx)
       {
         // Stale response, discard if success.
```
Comment (achamayou) [inline src/consensus/aft/raft.h:2476]:
```suggestion
        // Response about past indices, discard if success.
```

File: src/consensus/aft/test/committable_suffix.cpp [hunk 4]
```diff
@@ -0,0 +1,860 @@
...
+    B: Rolls back to 1.1
+
+    B: [1.1]
+    C: [1.1] 1.2
+    D: [1.1]
+    E: [1.1]
+
+  - At this point a committed index (1.2) is no longer present on a majority of
+    nodes. While C is unlikely to advertise it (fancy election rules mean
+    they're waiting for commit at 1.2) and will continue to share it, its
```
Comment (achamayou) [inline src/consensus/aft/test/committable_suffix.cpp:172]: Not sure I understand that bit. If it was practically committed, it must have been committable (ie. signed) and so if C participates there's a good chance it will win. This is all moot because the election could resolve without C of course, as rightly pointed out in the next line.

File: src/consensus/aft/test/committable_suffix.cpp [hunk 5]
```diff
@@ -0,0 +1,860 @@
...
+        else
+        {
+          ++it;
+        }
+      }
+    }
+
+    DOCTEST_REQUIRE(6 == dispatch_all(nodes, node_idA, channelsA->messages));
+
+    // NB: AppendEntriesResponses are not dispatched yet. So 1.4 is technically
```
Comment (achamayou) [inline src/consensus/aft/test/committable_suffix.cpp:299]: I think we ought to replace "technically committed" with "present on f+1 nodes", same with "True commit index", "Highest index present on f+1 nodes" etc, to distinguish that from commit index, which is what's advertised by the primary and eventually acknowledged by replicas.

File: src/consensus/aft/test/committable_suffix.cpp [hunk 6]
```diff
@@ -0,0 +1,860 @@
...
+  nodes[node_id##N] = &r##N; \
+  auto channels##N = channel_stub_proxy(r##N);
+
+/**
+  Summary of the behaviour this test aims to explore (for implementation reasons
+  the indices in the actual test don't match those in this comment, but the
+  logical relationships are the same):
+
+  - Produce an initial state where A is primary in term 1 of a 5-node network,
+    has mixed success replicating its entries. Local commit index is marked by
```
Comment (achamayou) [inline src/consensus/aft/test/committable_suffix.cpp:131]:
```suggestion
    has mixed success replicating its entries. Local view of the commit index is marked by
```

We've used (and continue to use I believe) "local commit index" with very different semantics.

**Review by achamayou — APPROVED** [review]

File: src/consensus/aft/test/committable_suffix.cpp (hunk 4 above)
Comment (eddyashton) [reply src/consensus/aft/test/committable_suffix.cpp:172]: I'll reword this. I was trying to say that the user-visible commit may not show the loss of persistence (ie - if C survives, then it _will_ share `1.2`, and that will be committed again, and the commit that a user could see won't move backwards). I think there may be space for an interesting distinction between the actual commit, and the user-visible commit, since the fancy election state lets a node know while have an inaccurate/lagging commit index? But as you say, that's all moot since there's still a fundamental persistence hole - _if_ C loses an election here, then we've lost persistence.

File: src/consensus/aft/test/committable_suffix.cpp (hunk 6 above)
Comment (eddyashton) [reply src/consensus/aft/test/committable_suffix.cpp:131]:
```suggestion
    has mixed success replicating its entries. Each node's commit index is marked by
```

File: src/consensus/aft/test/committable_suffix.cpp (hunk 4 above)
Comment (achamayou) [reply src/consensus/aft/test/committable_suffix.cpp:172]: Ah I see, advertise it to the user, I'd read that as advertise it in the election process. Yes, there is a distinction not just between "persisted by f+1 nodes" and "commit on leader", but also "commit as advertised by node to user".

File: src/consensus/aft/test/committable_suffix.cpp [hunk 7]
```diff
@@ -0,0 +1,865 @@
...
+    C: [1.1] 1.2
+    D: [1.1]
+    E: [1.1]
+
+  - Node C doesn't hear from B for long enough, and becomes primary. Its
+    AppendEntries are regularly lost. Eventually a heartbeat ("I'm at 1.2")
+    reaches Node B, which responds with a NACK ("I don't accept that tail").
+    Node C responds to that NACK with a better AppendEntries, which _should_
+    bring Node B back to the committed level, and forward to wherever C is.
+    However, under the current implementation, this AppendEntries may
```
Comment (jumaffre) [inline src/consensus/aft/test/committable_suffix.cpp:160]: "under the current implementation" will be outdated once this is merged. Should we briefly mention what the first implementation was instead?

**Review by jumaffre — APPROVED** [review]

File: src/consensus/aft/test/committable_suffix.cpp (hunk 7 above)
Comment (eddyashton) [reply src/consensus/aft/test/committable_suffix.cpp]: Good point, I've updated this comment.

```
However, if the AppendEntries returns an early-estimate of matching index
(as a previous implementation did), this AppendEntries may actually cause B
to roll back further than is safe, losing the committed state.
```
