### PR TITLE
Increase IOCTL padding, and introduce non-0 sentinels to confirm padding safety

### LINKED ISSUE #6956: Node crash on startup (memory corruption by writing past the attestation resp in the device)
UPD. Fixed in #6967 

```
/usr/bin/cchost --config cchost_config.json
...
541Z        0   [info ] /CCF/CCF/src/node/rpc/frontend.h:949 | Opening frontend
2025-04-03T08:34:45.488558Z        100 [debug] F/CCF/src/host/rpc_connections.h:388 | rpc connect request from enclave -1
2025-04-03T08:34:45.490238Z        0   [info ] node/quote_endorsements_client.h:116 | Fetching endorsements for attestation report at http://10.92.0.11:2377/metadata/THIM/amd/certification?platformId=9e61bfe8f4c40436c3c0255f6ea84d16709bb5d1f2f5a5d343e823db556ee973c6d649ab5533e0df39827908f54ed7de2e5b52e5554460ee727e841fb321ba5d&tcbVersion=db18000000000004
2025-04-03T08:34:45.490522Z        0   [fail ] _w/CCF/CCF/src/enclave/enclave.h:255 | Error starting node: OpenSSL error: error:03080106:digital envelope routines::passed invalid argument
2025-04-03T08:34:45.490660Z        100 [fail ] /__w/CCF/CCF/src/host/main.cpp:905   | An error occurred when creating CCF node: InternalError
```

```
cat /security-context-704636131/host-amd-cert-base64 
eyJ2Y2VrQ2VydCI6Ii0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLVxuTUlJRlF6Q0NBdmVnQXdJQkFnSUJBREJCQmdrcWhraUc5dzBCQVFvd05LQVBNQTBHQ1dDR1NBRmxBd1FDQWdVQVxub1J3d0dnWUpLb1pJaHZjTkFRRUlNQTBHQ1dDR1NBRmxBd1FDQWdVQW9nTUNBVEF3ZXpFVU1CSUdBMVVFQ3d3TFxuUlc1bmFXNWxaWEpwYm1jeEN6QUpCZ05WQkFZVEFsVlRNUlF3RWdZRFZRUUhEQXRUWVc1MFlTQkRiR0Z5WVRFTFxuTUFrR0ExVUVDQXdDUTBFeEh6QWRCZ05WQkFvTUZrRmtkbUZ1WTJWa0lFMXBZM0p2SUVSbGRtbGpaWE14RWpBUVxuQmdOVkJBTU1DVk5GVmkxTmFXeGhiakFlRncweU5UQXhNak15TURBd05UWmFGdzB6TWpBeE1qTXlNREF3TlRaYVxuTUhveEZEQVNCZ05WQkFzTUMwVnVaMmx1WldWeWFXNW5NUXN3Q1FZRFZRUUdFd0pWVXpFVU1CSUdBMVVFQnd3TFxuVTJGdWRHRWdRMnhoY21FeEN6QUpCZ05WQkFnTUFrTkJNUjh3SFFZRFZRUUtEQlpCWkhaaGJtTmxaQ0JOYVdOeVxuYnlCRVpYWnBZMlZ6TVJFd0R3WURWUVFEREFoVFJWWXRWa05GU3pCMk1CQUdCeXFHU000OUFnRUdCU3VCQkFBaVxuQTJJQUJJNTBlMXRySlhpUTk5a2g2QWFzR25jZVNDNERtSVdrcXN6WVZocEFOQ1Vva2RINzVmNlpidjQyNzVZelxueXZHTW1hVjdzaUdPZitETE84NlB5WGtyL2lVZkE1aGt5WEZIV0MyKzhldjJJcnRkNEo2YzZTMUJZbXY2dUo2SlxuTEdJUURhT0NBUmN3Z2dFVE1CQUdDU3NHQVFRQm5IZ0JBUVFEQWdFQU1CY0dDU3NHQVFRQm5IZ0JBZ1FLRmdoTlxuYVd4aGJpMUNNREFSQmdvckJnRUVBWng0QVFNQkJBTUNBUVF3RVFZS0t3WUJCQUdjZUFFREFnUURBZ0VBTUJFR1xuQ2lzR0FRUUJuSGdCQXdRRUF3SUJBREFSQmdvckJnRUVBWng0QVFNRkJBTUNBUUF3RVFZS0t3WUJCQUdjZUFFRFxuQmdRREFnRUFNQkVHQ2lzR0FRUUJuSGdCQXdjRUF3SUJBREFSQmdvckJnRUVBWng0QVFNREJBTUNBUmd3RWdZS1xuS3dZQkJBR2NlQUVEQ0FRRUFnSUEyekJOQmdrckJnRUVBWng0QVFRRVFKNWh2K2oweEFRMnc4QWxYMjZvVFJad1xubTdYUjh2V2wwMFBvSTl0VmJ1bHp4dFpKcTFVejROODVnbmtJOVU3WDNpNWJVdVZWUkdEdWNuNkVIN01odWwwd1xuUVFZSktvWklodmNOQVFFS01EU2dEekFOQmdsZ2hrZ0JaUU1FQWdJRkFLRWNNQm9HQ1NxR1NJYjNEUUVCQ0RBTlxuQmdsZ2hrZ0JaUU1FQWdJRkFLSURBZ0V3QTRJQ0FRQUltT1E2b2R1MTNmdVVqcVphV3FEMmlibmtYWSticzg4K1xuVEZ4R0hXUzVDVnA2NlB5Z2NKT3VMdW9aMms3V3NjTUk5QTlieCtjT3d2ZTBxY29UNDdMY1hjR2JQcnZWNzNva1xuZlYrR0ZodlpGM3paYm82eTlMTjViV0RHVW4zRGFETUc3WWtmMm00ZWozL0hyZnNsY21aRHBYR2ZOaHdRcW5VbVxuOTY4YlkzazMwMXBkUkIweUE5ZmxSNUNXVlpzajRYd1NUNFBnS3VPbHpJTXNMditudURNeTRhUmNSNnFCOVVpOVxuUWJxWlpPcDVnVzJFZ2ZSeHJxbFR1c1cvcDB5M21XdERFQWpiMGdKd3lRNTdyanBIZW5qUUp1ZGJUc2RoNWpqYlxuZjByZ0JFYVZVVWNaM29ORzRYbkNaUG9RNlBSZnFVaWQvYzFodTZWSXZDYU9EVGo2NTNlQmRiRUtycitnZ2I1ZlxuQnJXcjVYdG1wakNpbVJIWkwyYktzVkF6RlcyUnFqV0RwL1luMWV1dnlJdXl0NGcxMmZnWHVMYktQbGh6Y0dsN1xuQnJ5RnRXdDJKdCtHYllxaDhUWHRGSHlvUlIwNnZMd0RUZzA5YXg0VllqeXUxRmU1OTlQYVFxZHZtcFNpU3RES1xuN21zL0pnOFhrL0V3UlVOWitsZlJPMDdzc2ZkbzdaRWJqVFZaMmZaazVrY0Y2SlZtSzRPOVFvV2xkNm16azlHT1xuV2djTkE1QWRXK0ZxeDVYK0VJYlhGM1k4U2VVNFc2aG44dlhFMHNYcDN4V0hwQkhzM3ArRjJudDllYnRkWTBFK1xub24zSXJ3bnllYzl4WVduWHBxcXhVbkEvZWwyRThlVDZLY0VoeWRtYXk4Nnd0ZGgrdGhkQVBTTVE4SGZMMk9zWVxuVVFhREV2eVp6QT09XG4tLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tXG4iLCJ0Y2JtIjoiREIxODAwMDAwMDAwMDAwNCIsImNlcnRpZmljYXRlQ2hhaW4iOiItLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS1cbk1JSUdpVENDQkRpZ0F3SUJBZ0lEQVFBQk1FWUdDU3FHU0liM0RRRUJDakE1b0E4d0RRWUpZSVpJQVdVREJBSUNcbkJRQ2hIREFhQmdrcWhraUc5dzBCQVFnd0RRWUpZSVpJQVdVREJBSUNCUUNpQXdJQk1LTURBZ0VCTUhzeEZEQVNcbkJnTlZCQXNNQzBWdVoybHVaV1Z5YVc1bk1Rc3dDUVlEVlFRR0V3SlZVekVVTUJJR0ExVUVCd3dMVTJGdWRHRWdcblEyeGhjbUV4Q3pBSkJnTlZCQWdNQWtOQk1SOHdIUVlEVlFRS0RCWkJaSFpoYm1ObFpDQk5hV055YnlCRVpYWnBcblkyVnpNUkl3RUFZRFZRUUREQWxCVWtzdFRXbHNZVzR3SGhjTk1qQXhNREl5TVRneU5ESXdXaGNOTkRVeE1ESXlcbk1UZ3lOREl3V2pCN01SUXdFZ1lEVlFRTERBdEZibWRwYm1WbGNtbHVaekVMTUFrR0ExVUVCaE1DVlZNeEZEQVNcbkJnTlZCQWNNQzFOaGJuUmhJRU5zWVhKaE1Rc3dDUVlEVlFRSURBSkRRVEVmTUIwR0ExVUVDZ3dXUVdSMllXNWpcblpXUWdUV2xqY204Z1JHVjJhV05sY3pFU01CQUdBMVVFQXd3SlUwVldMVTFwYkdGdU1JSUNJakFOQmdrcWhraUdcbjl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUFuVTJkcnJOVGZiaE5RSWxsZitXMnkrUk9DYlN6SWQxYUtaZnRcbjJUOXpqWlFPempHY2NsMTdpMW1JS1dsN05UY0IwVllYdDNKeFpTek9aanNqTE5WQUVOMk1HajlUaWVkTCtRZXdcbktaWDBKbVFFdVlqbStXS2tzTHR4Z2RMcDlFN0VaTndORHFWMXIwcVJQNXRCOE9Xa3lRYklkTGV1NGFDejdqL1NcbmwxRmtCeXRldjlzYkZHenQ3Y3duanppOW03bm9xc2srdVJWQnAzK0luMzVRUGRjajhZZmxFbW5IQk52dVVESmhcbkxDSk1XOEtPalA2KytQaGJzM2lDaXRKY0FORXRXNHFUTkZvS1czQ0hsYmNTQ2pUTThLc05iVXgzQThlazVFVkxcbmpaV0gxcHQ5RTNUZnBSNlh5ZlFLblk2a2w1YUVJUHdkVzNlRllhcUNGUHJJbzlwUVQ2V3VEU1A0SkNZSmJabmVcbktLSWJaanpYa0p0M05RRzMyRXVrWUltQmI5U0NrbTkrZlM1TFpGZzlvanp1Yk1YMytOa0JvU1hJN09Qdm5ITXhcbmp1cDltdzVzZTZRVVY3R3FwQ0EyVE55cG9sbXVRK2NBYXhWN0pxSEU4ZGw5cFdmK1kzYXJiKzlpaUZDd0Z0NGxcbkFsSnc1RDBDVFJUQzFZNVlXRkRCQ3JBL3ZHbm1UbnFHOEMrampVQVM3Y2pqUjhxNE9QaHlEbUpSUG5hQy9aRzVcbnVQMEswejZHb08vM3Vlbjl3cXNoQ3VIZWdMVHBPZUhFSlJLclFGcjRQVkl3Vk9CMCtlYk81RmdveU93NDNueUZcbkQ1VUtCRHhFQjRCS28vMHVBaUtITFJ2dmdMYk9SYlU4S0FSSXMxRW9xRWptRjhVdHJtUVdWMmhVand6cXd2SEZcbmVpOHJQeE1DQXdFQUFhT0JvekNCb0RBZEJnTlZIUTRFRmdRVU84WnVHQ3JEL1QxaVpFaWI0N2RITExUOHYvZ3dcbkh3WURWUjBqQkJnd0ZvQVVoYXdhMFVQM3lLeFYxTVVkUVVpcjFYaEsxRk13RWdZRFZSMFRBUUgvQkFnd0JnRUJcbi93SUJBREFPQmdOVkhROEJBZjhFQkFNQ0FRUXdPZ1lEVlIwZkJETXdNVEF2b0MyZ0s0WXBhSFIwY0hNNkx5OXJcblpITnBiblJtTG1GdFpDNWpiMjB2ZG1ObGF5OTJNUzlOYVd4aGJpOWpjbXd3UmdZSktvWklodmNOQVFFS01EbWdcbkR6QU5CZ2xnaGtnQlpRTUVBZ0lGQUtFY01Cb0dDU3FHU0liM0RRRUJDREFOQmdsZ2hrZ0JaUU1FQWdJRkFLSURcbkFnRXdvd01DQVFFRGdnSUJBSWdlVVFTY0FmM2xEWXFnV1UxVnRsRGJtSU44UzJkQzVrbVF6c1ovSHRBalFuTEVcblBJMWpoM2dKYkx4TDZnZjNLOGp4Y3R6T1dua1ljYmRmTU9PcjI4S1QzNUlhQVIyMHJla0tSRnB0VEhoZStERnJcbjNBRnpaTEREN2NXSzI5L0dwUGl0UEpES0N2STdBNFVnMDZyazdKMHpCZTFmei9xZTRpMi9GMTJydmZ3Q0dZaGNcblJ4UHk3UUYzcThmUjZHQ0pkQjFVUTVTbHdDakZ4RDR1ZXpVUnp0SWxJQWpNa3Q3REZ2S1JoKzJ6Sys1cGxWR0dcbkZzakRKdE16MnVkOXkwcHZPRTRqM2RINUlXOWpHeGFTR1N0cU5yYWJubnBGMjM2RVRyMS9hNDNiOEZGS0w1UU5cbm10OFZyOXhuWFJwem5xQ1J2cWpyK2tWcmI2ZGxmdVRsbGlYZVFUTWxCb1JXRkpPUkw4QWNCSnhHWjRLMm1YZnRcbmwxalU1VExlaDVLWEw5Tlc3YS9xQU9JVXMyRmlPaHFydHpBaEpSZzlJajhRa1E5UGsrY0tHenc2RWwzVDNrRnJcbkVnNnpreG12TXVhYlpPc2RLZlJrV2ZoSDJaS2NUbERmbUgxSDB6cTBRMmJHM3V2YVZkaUN0RlkxTGxXeUIzOEpcblMyZk5zUi9QeTZ0NWJyRUpDRk52emFEa3k2S2VDNGlvbi9jVmdVYWk3enpTM2JHUVd6S0RLVTM1U3FOVTJXa1Bcbkk4eENaMDBXdElpS0tGblhXVVF4dmxLbW1nWkJJWVBlMDF6RDBOOGF0RnhtV2lTbmZKbDY5MEI5ckpwTlIvZklcbmFqeENXM1NlaXdzNnIxWm0rdEN1VmJNaU50cFM5VGhqTlg0dXZlNXRoeWZFMkRnb3hSRnZZMUNzb0Y1TVxuLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLVxuLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tXG5NSUlHWXpDQ0JCS2dBd0lCQWdJREFRQUFNRVlHQ1NxR1NJYjNEUUVCQ2pBNW9BOHdEUVlKWUlaSUFXVURCQUlDXG5CUUNoSERBYUJna3Foa2lHOXcwQkFRZ3dEUVlKWUlaSUFXVURCQUlDQlFDaUF3SUJNS01EQWdFQk1Ic3hGREFTXG5CZ05WQkFzTUMwVnVaMmx1WldWeWFXNW5NUXN3Q1FZRFZRUUdFd0pWVXpFVU1CSUdBMVVFQnd3TFUyRnVkR0VnXG5RMnhoY21FeEN6QUpCZ05WQkFnTUFrTkJNUjh3SFFZRFZRUUtEQlpCWkhaaGJtTmxaQ0JOYVdOeWJ5QkVaWFpwXG5ZMlZ6TVJJd0VBWURWUVFEREFsQlVrc3RUV2xzWVc0d0hoY05NakF4TURJeU1UY3lNekExV2hjTk5EVXhNREl5XG5NVGN5TXpBMVdqQjdNUlF3RWdZRFZRUUxEQXRGYm1kcGJtVmxjbWx1WnpFTE1Ba0dBMVVFQmhNQ1ZWTXhGREFTXG5CZ05WQkFjTUMxTmhiblJoSUVOc1lYSmhNUXN3Q1FZRFZRUUlEQUpEUVRFZk1CMEdBMVVFQ2d3V1FXUjJZVzVqXG5aV1FnVFdsamNtOGdSR1YyYVdObGN6RVNNQkFHQTFVRUF3d0pRVkpMTFUxcGJHRnVNSUlDSWpBTkJna3Foa2lHXG45dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBMExkNTJSSk9kZWlKbHFLMkpkc1ZtRDdGa3R1b3RXd1gxZk5nXG5XNDFYWTlYejFIRWhTVW1oTHo5Q3U5REhSbHZnSlNOeGJlWVlzbkpmdnlqeDFNZlUwVjV0a0tpVTFFZXNORnRhXG4xa1RBMHN6TmlzZFljOWlzcWs3bVhUNStLZkdSYmZjNFYvOXpSSWNFOGpsSE42MVMxanU4WDkzKzZkeERVckcyXG5TenhxSjRCaHF5WW1VRHJ1UFhKU1g0dlVjMDFQN2o5OE1wcU9TOTVyT1JkR0hlSTUyTmF6NW0yQitPK3Zqc0MwXG42MGQzN2pZOUxGZXVPUDRNZXJpOHFnZmkyUzVrS3FnL2FGNmFQdHVBWlFWUjd1M0tGWVhQNTlYbUpndGNvZzA1XG5nbUkwVC9PaXRMaHV6VnZwWmNMcGgwb2RoLzFJUFhxeDMrTW5qRDk3QTdmWHBxR2QveThLeFg3amtzVEV6QU9nXG5iS0FlYW0zbG0rM3lLSWNUWU1sc1JNWFBjak5iSXZtc0J5a0QvL3hTbml1c3VIQmtnbmxFTkVXeDFVY2JRUXJzXG4rZ1ZEa3VWUGhzbnpJUk5nWXZNNDhZKzdMR2lKWW5ybUU4eGNyZXhla0J4cnZhMlY5VEpRcW5OM1E1M2t0NXZpXG5RaTMrZ0NmbWt3QzBGMHRpcklaYkxrWFByUHd6WjBNOWVOeGhJeVNiMm5wSmZnbnF6NTVJMHUzM3doNHIwWk5RXG5lVEdmdzAzTUJVdHl1ekdlc0drY3crbG9xTWFxMXFSNHRqR2JQWXhDdnBDcTcrT2dwQ0NvTU5pdDJ1TG85TTE4XG5mSHoxMGxPTVQ4bldBVXZSWkZ6dGVYQ20rN1BIZFlQbG1Rd1V3M0x2ZW5KL0lMWG9RUEhmYmtIMEN5UGZobDFqXG5XaEpGWmFzQ0F3RUFBYU4rTUh3d0RnWURWUjBQQVFIL0JBUURBZ0VHTUIwR0ExVWREZ1FXQkJTRnJCclJRL2ZJXG5yRlhVeFIxQlNLdlZlRXJVVXpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTURvR0ExVWRId1F6TURFd0w2QXRvQ3VHXG5LV2gwZEhCek9pOHZhMlJ6YVc1MFppNWhiV1F1WTI5dEwzWmpaV3N2ZGpFdlRXbHNZVzR2WTNKc01FWUdDU3FHXG5TSWIzRFFFQkNqQTVvQTh3RFFZSllJWklBV1VEQkFJQ0JRQ2hIREFhQmdrcWhraUc5dzBCQVFnd0RRWUpZSVpJXG5BV1VEQkFJQ0JRQ2lBd0lCTUtNREFnRUJBNElDQVFDNm0wa0RwNnp2NE9qZmd5K3psZWVoc3g2b2wwb2NnVmVsXG5FVG9icHgrRXVDc3FWRlJQSzFqWjFzcC9seWQ5KzBmUTByNjZuN2thZ1JrNENhMzlnNjZXR1RKTWVKZHFZcml3XG5TVGpqRENLVlBTZXNXWFlQVkF5RGhtUDVuMnYrQllpcFpXaHB2cXBhaU8rRUdLNUlCUCs1NzhRZVcvc1Nva3JLXG5kSGFMQXhHMkxoWnhqOWFGNzNmcUM3T0FKWjVhUG9udzRSRTI5OUZWYXJoMVR4MmVUM3dZ2tEZ3V0Q1RCMVlxXG56VDVEdXd2QWUrY28yQ0lWSXpNRGFtWXVTRmpQTjBCQ2dvamw3VitiVG91N2RNc3FJdS9UVy9yUENYOS9FVWNwXG5LR0txUFEzUCtOOXIxaGpFRlkxcGxCZzkzdDUzT09vNDlHTkkrVjF6dlhQTEk2eElGVnNoK210bzJSdGdFWC9lXG5wbU1LVE5ONnBzVzg4cWc3YzFoVFd0TjZNYlJ1UTB2bStPKy8ydEtCRjJoOFRIYjk0T3Z2SEhvRkRwYkNFTGxxXG5IbklZaHh5MFlLWEd5YVcxTmpmVUx4cnJteFZXNHdjbjVFOEdkZG12TmE2eVltOHNjSmFnRWkxM21oR3U0SnFoXG4zUVUzc2Y4aVVTVXIwOXhRRHdIdE9RVVZJcXg0bWFCWlBCdFNNZitxVUR0alhTU3E4bGZXY2Q4YkxyOW1kc1VuXG5KWkowK3R1UE1LbUJuU0g4NjBsbEtrK1ZwVlFzZ3FiekRJdk9MdkQ2VzFVbXEyNWJveENZSitUdUJvYTRzK0hIXG5DVmlBdmdUOWtmL3JCcTFkK2l2ajZza2tIeHV6Y3hiazF4djZaR3hydGVKeFZIN0tsWDdZUmRaNmVBUkt3TGU0XG5BRlpFQXdvS0NRPT1cbi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS1cbiIsImNhY2hlQ29udHJvbCI6Ijg2NDAwIn0=
```

### PR DESCRIPTION
**Pull request by eddyashton**
Should resolve #6956.

Further discussion in that ticket, but in summary our IOCTL call to `SEV_SNP_GUEST_MSG_REPORT` was passing too-small a struct, resulting in memory corruption as the response was written to our stack. Our `SafetyPadding` protection didn't catch this because the additional bytes were all 0s - the IOCTL zero'd both the padding bytes _and_ further data.

This separates the padding (the IOCTL is going to write some large struct that we don't fully parse/specify) from the sentinel/protection bytes (we want to catch if it writes beyond these bytes). The padding is increased to create a 4k struct, matching the kernel definition, and the sentinel bytes now contain some non-0 values.

Additionally, we add a unit test that fetches the attestation, which should now fail if the padding/sentinel protection is violated.

### CODE REVIEW

File: include/ccf/pal/snp_ioctl6.h [hunk 1]
```diff
@@ -23,21 +23,74 @@ namespace ccf::pal::snp::ioctl6
...
+    static constexpr uint8_t post_sentinel_first = 0xCC;
+    static constexpr uint8_t post_sentinel_last = 0xDD;
+
+    uint8_t pre_sentinels[num_sentinel_bytes] = {0};
+    T data;
+    uint8_t post_sentinels[num_sentinel_bytes] = {0};
+
+    IoctlSentinel()
+    {
+      pre_sentinels[0] = pre_sentinel_first;
```
Comment (maxtropets) [inline include/ccf/pal/snp_ioctl6.h:56]: Why not `memset` to be all sentinel values?..

File: include/ccf/pal/snp_ioctl6.h [hunk 2]
```diff
@@ -135,10 +188,18 @@ namespace ccf::pal::snp::ioctl6
      * psp-sev.h) */
     ExitInfo exit_info;
   };
+
+  // This 4000 comes from the definition of snp_report_resp in
+  // https://github.com/torvalds/linux/blob/master/include/uapi/linux/sev-guest.h
+  // EDA: Temporarily decreased this, to confirm that tests now fail loudly. DO
```
Comment (maxtropets) [inline include/ccf/pal/snp_ioctl6.h:194]: do-not-merge-guarg

File: include/ccf/pal/snp_ioctl6.h [hunk 3]
```diff
@@ -135,10 +188,18 @@ namespace ccf::pal::snp::ioctl6
...
+  // NOT MERGE
+  using PaddedAttestationResp = PaddedTo<AttestationResp, 1500>;
+  using PaddedDerivedKeyResp = PaddedTo<DerivedKeyResp, 4000>;
```
Comment (maxtropets) [inline include/ccf/pal/snp_ioctl6.h:197]: Worth making 8KB or smth? Shall be harmless, but will detect writing past the usual 4k

File: include/ccf/pal/snp_ioctl6.h (hunk 1 above)
Comment (maxtropets) [reply include/ccf/pal/snp_ioctl6.h:59]: Agree, I'm just against zeros in the middle

File: include/ccf/pal/snp_ioctl6.h (hunk 3 above)
Comment (maxtropets) [reply include/ccf/pal/snp_ioctl6.h:201]: Or at least +32 bytes extra, if 8kb is an overkill

Comment (eddyashton) [reply include/ccf/pal/snp_ioctl6.h:201]: The actual type is an `IoctlSentinel<PaddedXXXResp>`, which will detect writes 1k (either side!) of this padded buffer. We _could_ safely increase this padding beyond 4k, to give us headroom if the underlying struct type increases in size. But I think that's unlikely. I think this separation of types between a padded type (an overallocation that the underlying thing may write to) and a sentinel type (we detect if it writes beyond) is helpful, and we should keep the padded size to a justifiable value (eg - what the kernel device uses).

Comment (maxtropets) [reply include/ccf/pal/snp_ioctl6.h:201]: My sense is that `IoctlSentinel` contains a porinter to `resp`, meaning that padding around `resp` type may by actually useful, whereas padding around the top-level struct is probably much less useful.

But feel free to merge is.

Comment (maxtropets) [reply include/ccf/pal/snp_ioctl6.h:201]: Ok, I checked out the branch to see the file in full. 

> which will detect writes 1k (either side!) 
I now see the difference, we have sentinels on both sides and padding simply as extra buffer, no checks. Got it.

File: include/ccf/pal/snp_ioctl6.h [hunk 4]
```diff
@@ -135,10 +192,18 @@ namespace ccf::pal::snp::ioctl6
      * psp-sev.h) */
     ExitInfo exit_info;
   };
+
+  // This 4000 comes from the definition of snp_report_resp in
+  // https://github.com/torvalds/linux/blob/master/include/uapi/linux/sev-guest.h
+  // EDA: Temporarily decreased this, to confirm that tests now fail loudly. DO
+  // NOT MERGE
+  using PaddedAttestationResp = PaddedTo<AttestationResp, 1500>;
```
Comment (maxtropets) [inline include/ccf/pal/snp_ioctl6.h:200]:
```suggestion
  using PaddedAttestationResp = PaddedTo<AttestationResp, 4000>;
```

File: include/ccf/pal/snp_ioctl6.h [hunk 5]
```diff
@@ -135,10 +192,18 @@ namespace ccf::pal::snp::ioctl6
      * psp-sev.h) */
     ExitInfo exit_info;
   };
+
+  // This 4000 comes from the definition of snp_report_resp in
+  // https://github.com/torvalds/linux/blob/master/include/uapi/linux/sev-guest.h
+  // EDA: Temporarily decreased this, to confirm that tests now fail loudly. DO
+  // NOT MERGE
```
Comment (maxtropets) [inline include/ccf/pal/snp_ioctl6.h:199]:
```suggestion
  // EDA: Temporarily decreased this, to confirm that tests now fail loudly. DO
  // NOT MERGE
```
```suggestion
  // This 4000 comes from the definition of snp_report_resp in
  // https://github.com/torvalds/linux/blob/master/include/uapi/linux/sev-guest.h
```

Comment (maxtropets) [inline include/ccf/pal/snp_ioctl6.h:199]:
```suggestion
  // This 4000 comes from the definition of snp_report_resp in
  // https://github.com/torvalds/linux/blob/master/include/uapi/linux/sev-guest.h
```
