### PR TITLE
Re-hauling encryptor for multi-threading

### LINKED ISSUE #1567: Combine the CFT and BFT encryptors
We currently have a BFT and CFT encryptors. We need to look into combining them so that we only have 1 encryptor, if this is at all possible.

### LINKED ISSUE #1986: Getting compacted keys from a later primary does not work
When a node joins, it is given the list of compacted ledger secrets from the current primary. This lets it replay the ledger/incoming append entries, and while doing so it calls `encryptor->compact` at each signature transaction, and tries to compact its own list of ledger secrets. This call to `record_compacted_keys` simply appends the given secret to the same list we received from the primary, so we end up with duplicates. If the primary told us secrets at versions `[1, 32, 46, 85]`, we'll end up with `[1, 32, 46, 85, 32, 46, 85]`. If we then become primary, this is the list we'll send to new joiners, and the duplicates will cause them to loop forever.

This is the cause of [this test failure](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=16293&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=63d660c3-6f76-573a-0154-fd0bcb096ded&l=13261) - node 8 gets stuck in a permanent loop adding to a container, eventually timing out or hitting a `bad_alloc`. This has a high repro rate on this seed, but is not 100%. We should add a reconfiguration suite which exhibits this crash consistently.

There's several things we should or could fix here:
- When we get a list of secrets from the primary, we should make sure that the versions they apply from are unique and ordered.
- When we `record_compacted_keys`, we should check if this is a secret we already know (if so, it should match!), rather than apppending out-of-order.
- `TxEncryptor::compact` should be rewritten to be clearer, and to remove the possibility of looping forever.
- We should add some logging on rekeying/key compaction, so that verbose logs show us the lifetime of a secret.
- The 'active' `encryption_keys` and compacted `ledger_secrets` could be combined into a single, ordered container. We want to keep the lookup on `get_encryption_key` cheap, but we can do this by looking at the final item first (which is always the secret we want on the hot path), and only running the `std::upper_bound` search if that fails.
- We should investigate what we're doing with very old ledger secrets. With snapshotting, we don't want to keep them around forever, but this might mean declaring that only snapshots created in the last N secrets can be used for joining (for anything older, the primary doesn't remember how you should decrypt it, and finding out by trawling backwards through the ledger is too expensive).

### PR DESCRIPTION
**Pull request by jumaffre**
Fixes #1986
Fixes #1567 
And item 1. from #2020 

As per #1986 and #2020, there were some issues with the way CCF was managing ledger secrets. This PR fixes those as well as combine the CFT and BFT encryptors which used a different IV. In particular:

- CFT and BFT encryptors are unified. The IV used now depends on `{KV seqno, term, is_snapshot}` so that the IV isn't re-used but yet produces the same encrypted write sets from the same input in BFT mode (see `encryptor.h`) 
- The `ccf.secrets` table is now keyed by node id so that it easy for a node to take a read dependency on that table when accessing the ledger secrets (see following point)
- Accessing the ledger secrets now require a `kv::Tx` which takes a read dependency on the `ccf.secrets` table so that concurrent rekey (which write the new encrypted secret to that table for all nodes) operations will result in a KV conflict.
- Because the join procedure is a three-step procedure (added as pending -> node is trusted by consortium -> node requests network secrets) and the new joiner only needs the ledger secrets up to the seqno it is trusted, CCF records the version of the latest ledger secret when a node is trusted and only release ledger secrets until then. Future ledger secrets are passed through the `ccf.secrets` table.

### CODE REVIEW

File: src/crypto/symmetric_key.h [hunk 1]
```diff
@@ -19,7 +19,7 @@ namespace crypto
     uint8_t iv[SIZE_IV] = {};
 
     // 12 bytes IV with 8 LSB are unique sequence number
-    // and 4 MSB are 4 LSB of unique id (Node id or View)
+    // and 4 MSB are 4 LSB of term (with last bit indicating a snapshot)
```
Comment (achamayou) [inline src/crypto/symmetric_key.h:22]: Can we use "view" rather than "term" here, since this is a cross-consensus concern.

File: src/kv/encryptor.h [hunk 2]
```diff
@@ -2,144 +2,82 @@
...
-
-      return search->key;
+      // IV is function of seqno, term and snapshot so that:
+      // - Same seqno across rollbacks does not reuse IV
+      // - Snapshots do not reuse IV
+      // - If all nodes execute the _same_ tx (or generate the same snapshot),
+      // the same IV will be used
+
+      hdr.set_iv_seq(version);
+      hdr.set_iv_term(term);
```
Comment (achamayou) [inline src/kv/encryptor.h:28]: "view" here and elsewhere please.

File: src/kv/generic_serialise_wrapper.h [hunk 3]
```diff
@@ -50,6 +50,7 @@ namespace kv
     W private_writer;
     W* current_writer;
     Version version;
+    Term term; // Used for encryption IV only
```
Comment (achamayou) [inline src/kv/generic_serialise_wrapper.h:53]: Taking a TxID down that path may end up being a little cleaner.

File: src/node/ledger_secrets.h [hunk 4]
```diff
@@ -3,118 +3,282 @@
...
+    {
+      // Ledger secrets are not stored in the KV. Instead, they are
+      // cached in a unique LedgerSecrets instance that can be accessed without
+      // reading the KV. However, it is possible that the ledger secrets are
+      // updated (e.g. rekey tx) concurrently to their access by another tx. To
+      // prevent conflicts, accessing the ledger secrets require access to a tx
+      // object, which must take a dependency on the secrets table.
+      auto v = tx.get_view(secrets_table);
+
+      // Taking a depency on the key at self, which would get updated on rekey
```
Comment (achamayou) [inline src/node/ledger_secrets.h:109]:
```suggestion
      // Taking a read dependency on the key at self, which would get updated on rekey
```

File: src/node/node_state.h [hunk 5]
```diff
@@ -1597,85 +1552,65 @@ namespace ccf
...
+                   ledger_secret_set.encrypted_secrets)
               {
-                if (encrypted_secret_for_node.node_id == self)
+                auto plain_ledger_secret = LedgerSecretsBroadcast::decrypt(
+                  node_encrypt_kp,
+                  tls::make_public_key(
+                    ledger_secret_set.primary_public_encryption_key),
+                  encrypted_ledger_secret.encrypted_secret);
+
+                // On rekey, the version is infered from the version at which
```
Comment (achamayou) [inline src/node/node_state.h:1585]:
```suggestion
                // On rekey, the version is inferred from the version at which
```

File: src/crypto/symmetric_key.h (hunk 1 above)
Comment (jumaffre) [reply src/crypto/symmetric_key.h:22]: As discussed, let's stick to "term" as this comes from the KV directly, which refers to consensus view as "term" so that it's not confused with a `kv::Tx`'s view.

File: src/kv/encryptor.h (hunk 2 above)
Comment (jumaffre) [reply src/kv/encryptor.h:32]: Same as above.

File: src/kv/generic_serialise_wrapper.h (hunk 3 above)
Comment (jumaffre) [reply src/kv/generic_serialise_wrapper.h]: Done.

File: src/crypto/symmetric_key.h [hunk 6]
```diff
@@ -40,16 +40,16 @@ namespace crypto
       *reinterpret_cast<uint64_t*>(iv) = seq;
     }
 
-    void set_iv_id(uint64_t id)
+    void set_iv_term(uint64_t term)
```
Comment (ashamis) [inline src/crypto/symmetric_key.h:43]: nit: I think this should be view

Comment (jumaffre) [reply src/crypto/symmetric_key.h:43]: As discussed in another comment, the KV uses `term` rather than view so that it's not confused with a `kv::Tx`'s view. Because the KV drives the encryptor, I think it is preferable to use `term` here.

Comment (achamayou) [reply src/crypto/symmetric_key.h:43]: If/when we kill off usage of the "view" in "get_view" in the KV and the associated view types, we can do this rename. But until then, we're better off not having two different concepts called "views" in KV.

Another possibility, is to use consensus_view/ConsensusView for this in the KV.

**Review by achamayou — APPROVED** [review]

File: src/kv/encryptor.h [hunk 7]
```diff
@@ -2,144 +2,85 @@
...
-     *
-     * @param[in]   plain             Plaintext to encrypt
-     * @param[in]   additional_data   Additional data to tag
-     * @param[out]  serialised_header Serialised header (iv + tag)
-     * @param[out]  cipher            Encrypted ciphertext
-     * @param[in]   version           Version used to retrieve the corresponding
-     * encryption key
-     * @param[in]   is_snapshot       Indicates that the entry is a snapshot (to
-     * avoid IV re-use)
-     */
```
Comment (eddyashton) [inline src/kv/encryptor.h:97]: Why have we lost these docs?

File: src/node/ledger_secrets.h [hunk 8]
```diff
@@ -3,118 +3,283 @@
...
+
+    LedgerSecret(const LedgerSecret& other) :
+      raw_key(other.raw_key),
+      key(std::make_shared<crypto::KeyAesGcm>(other.raw_key))
+    {}
+
+    LedgerSecret(std::vector<uint8_t>&& raw_key_) :
+      raw_key(raw_key_),
+      key(std::make_shared<crypto::KeyAesGcm>(std::move(raw_key_)))
+    {}
```
Comment (eddyashton) [inline src/node/ledger_secrets.h:37]: Why do we call `make_shared` here - can't we copy-construct/move the original `key` directly?

```suggestion
    LedgerSecret(const LedgerSecret& other) :
      raw_key(other.raw_key),
      key(other.key)
    {}

    LedgerSecret(std::vector<uint8_t>&& raw_key_) :
      raw_key(raw_key_),
      key(std::move(other.key))
    {}
```

File: src/node/ledger_secrets.h [hunk 9]
```diff
@@ -3,118 +3,283 @@
...
+
+  inline LedgerSecret make_ledger_secret()
+  {
+    return LedgerSecret(tls::create_entropy()->random(crypto::GCM_SIZE_KEY));
+  }
+
+  using VersionedLedgerSecret = std::pair<kv::Version, LedgerSecret>;
+  using LedgerSecretsMap = std::map<kv::Version, LedgerSecret>;
+
+  struct VersionedLedgerSecrets
```
Comment (eddyashton) [inline src/node/ledger_secrets.h:48]: These names are a little confusing. I'd expect `VersionedLedgerSecrets` to be a collection of `VersionedLedgerSecret`s, but its actually a thin wrapper around `LedgerSecretsMap`. Why do we need this wrapper rather than `LedgerSecretsMap` directly? And if we only use `VersionedLedgerSecret` (singular) rarely/internally, `LedgerSecretsMap::value_type` may be clearer?

File: src/node/ledger_secrets.h [hunk 10]
```diff
@@ -3,118 +3,283 @@
...
+      if (search == search_begin)
+      {
+        throw std::logic_error(fmt::format(
+          "kv::TxEncryptor: could not find ledger encryption key for seqno {}",
+          version));
+      }
+      return --search;
+    }
+
+    void take_dependency_on_secrets(kv::Tx& tx)
```
Comment (eddyashton) [inline src/node/ledger_secrets.h:99]: I think this should be `ReadOnlyTx` and `get_read_only_view`. We don't use this in many places but if we did, we could get `const`-like type-safety by using `ReadOnlyTx` throughout some execution stacks.

File: src/node/ledger_secrets.h [hunk 11]
```diff
@@ -3,118 +3,283 @@
...
       }
-      return secrets_list.back().secret;
+
+      auto latest_ledger_secret = ledger_secrets.secrets.rbegin();
+      return std::make_pair(
+        latest_ledger_secret->first, latest_ledger_secret->second);
     }
 
-    std::optional<LedgerSecret> get_penultimate()
+    std::optional<LedgerSecret> get_penultimate(kv::Tx& tx)
```
Comment (eddyashton) [inline src/node/ledger_secrets.h:170]: I think we should change this function to fetch both latest and penultimate under the same lock. If a secret is added after fetching one and before fetching the other, we encrypt junk.

File: src/node/ledger_secrets.h [hunk 12]
```diff
@@ -3,118 +3,283 @@
...
+
+    void take_dependency_on_secrets(kv::Tx& tx)
+    {
+      // Ledger secrets are not stored in the KV. Instead, they are
+      // cached in a unique LedgerSecrets instance that can be accessed without
+      // reading the KV. However, it is possible that the ledger secrets are
+      // updated (e.g. rekey tx) concurrently to their access by another tx. To
+      // prevent conflicts, accessing the ledger secrets require access to a tx
+      // object, which must take a dependency on the secrets table.
+      auto v = tx.get_view(secrets_table);
```
Comment (eddyashton) [inline src/node/ledger_secrets.h:107]:
```suggestion
      auto v = tx.get_view<Secrets>(Tables::SECRETS);
```

If we lookup this table by name, we can remove the ref member, and remove the constructor argument, and remove some of the changes to test cases where this no longer needs to be passed.

File: src/kv/encryptor.h (hunk 7 above)
Comment (jumaffre) [reply src/kv/encryptor.h]: Because I re-wrote this class from scratch and forgot to add this back - well spotted! I've added it back.

File: src/node/ledger_secrets.h (hunk 10 above)
Comment (jumaffre) [reply src/node/ledger_secrets.h:99]: Good point. Changed now.

File: src/node/ledger_secrets.h (hunk 11 above)
Comment (jumaffre) [reply src/node/ledger_secrets.h]: Good point. Done now.

File: src/node/ledger_secrets.h (hunk 12 above)
Comment (jumaffre) [reply src/node/ledger_secrets.h]: Ah! True. I forgot we could do that 👍

File: src/node/ledger_secrets.h (hunk 9 above)
Comment (jumaffre) [reply src/node/ledger_secrets.h]: Done.

File: src/node/ledger_secrets.h (hunk 8 above)
Comment (jumaffre) [reply src/node/ledger_secrets.h]: For the copy constructor, yes. The second one isn't the move constructor so we still need the `make_shared` to create the key.
