### PR TITLE
JS FFI exception safety update

### LINKED ISSUE #5589: JS Runtime memory limit is not applied correctly
Issue spotted during work on #5564, and confirmed in #5588.

Depending on the situation in which the max heap size set by `JS_SetMemoryLimit()` is reached, the `ccf::js::Runtime` may cause a crash, rather than return an HTTP error response.

There are three situations in which we can reach the heap size limit:

1. As we construct globals, before (and after) the interpreter invocation
3. During JS execution
4. Inside a JS wrapper to a C++ call

Only situation 2 is handled correctly at the moment. #5588 confirms that situation is not correctly handled and can lead to a crash.

Situation 3 isn't tested yet, but almost certainly suffers from the same issue.

There is also a problem in situation 3, where some C++ exceptions may lead to a leak from the JS interpreter, since closing the Context may not free all memory allocated through JS calls. Further investigation is needed there.

### PR DESCRIPTION
**Pull request by achamayou**
Closes #5589.

I have now done a first pass on all the calls listed in the issue. There is still scope for cleanup, in particular in governance code where we don't use safe wrappers as extensively as we should. I've already removed some unused wrappers, but I'm still finding some.

I've had a look at removing the JSValue& conversion on the WrappedValue, but it's massive amount of further changes, and it's not necessary to fix the leak, so I think I would like to go ahead with this and unblock #5740.

Another thing that I've put in a pin in for now is that the crypto code (ie. wrappers for OpenSSL) mostly (but not exclusively) throws std::runtime_error to indicate validation failures, and std::logic_error is used for more internal failures. It's important to distinguish them when we validate an x509 chain for example, with some fuzziness. If one of the values in the chain is not a valid PEM for example, is that False or exception (I think it's exception, but it's arguable). Filed as #5760.

### CODE REVIEW

File: src/js/wrap.h [hunk 1]
```diff
@@ -160,35 +232,61 @@ namespace ccf::js
       return JSWrappedValue(ctx, JS_GetProperty(ctx, val, prop));
     }
 
-    void set(const char* prop, const JSWrappedValue& value) const
+    int set(const char* prop, const JSWrappedValue& value) const
```
Comment (eddyashton) [inline src/js/wrap.h:235]: It looks like most of the uses of this want `std::move` to get the other overload. When do we use this `const&` instance?

Comment (achamayou) [reply src/js/wrap.h:235]: I don't know, but that's a good question to answer once I'm done making the FFI safe I think.

Another thing that I've put in a pin in for now is that the crypto code (ie. wrappers for OpenSSL) mostly (but not exclusively) throws std::runtime_error to indicate validation failures, and std::logic_error is used for more internal failures. It's important to distinguish them when we validate an x509 chain for example, with some fuzziness. If one of the values in the chain is not a valid PEM for example, is that False or exception (I think it's exception, but it's arguable).

Comment (achamayou) [reply src/js/wrap.h:240]: > When do we use this const& instance?

The answer was, nowhere legitimate, that's cleaned up now. Separately, I seem to have introduced a double free in historical queries, chasing that now...

File: src/js/wrap.h [hunk 2]
```diff
@@ -100,6 +127,51 @@ namespace ccf::js
...
+  {
+  public:
+    JSWrappedAtom() : ctx(NULL), val(JS_ATOM_NULL) {}
+    JSWrappedAtom(JSContext* ctx, JSAtom&& val) : ctx(ctx), val(std::move(val))
+    {}
+    JSWrappedAtom(JSContext* ctx, const JSAtom& value) : ctx(ctx)
+    {
+      val = JS_DupAtom(ctx, value);
+    }
+    JSWrappedAtom(const JSWrappedAtom& other) : ctx(other.ctx)
```
Comment (eddyashton) [inline src/js/wrap.h:140]: Similar to `JSWrappedValue`, it would be good if we could remove this `const&` overload, so that we get compile-time errors if we fail to `move`/`take` an argument.

Comment (achamayou) [reply src/js/wrap.h:140]: Agreed!

**Review by eddyashton — APPROVED** [review]
