### PR TITLE
Fix and re-enable task demo test

### LINKED ISSUE #7331: task_system_demo test failure
```
CCF/src/tasks/test/demo/main.cpp:101:
TEST CASE:  PauseAndResume

CCF/src/tasks/test/demo/main.cpp:220: FATAL ERROR: REQUIRE( x.load() == 204 ) is NOT correct!
  values: REQUIRE( 205 == 204 )
```

https://github.com/microsoft/CCF/actions/runs/18341945046/job/52239592799?pr=7328

### PR DESCRIPTION
**Pull request by maxtropets**
Closes #7331 

Current behaviour
- By calling `cancel_task()` interface, task itself is cancelled, actions "in flight" are not
- `OrderedTasks` grabs a bundle of actions and doesn't support cancelling midway through
- The original test only worked (90% of the time) because of the race condition

This approach is to be disputed elsewhere, this PR only came out to bring back demo tests.

### CODE REVIEW

File: src/tasks/test/demo/main.cpp [hunk 1]
```diff
@@ -213,10 +212,13 @@ TEST_CASE("PauseAndResume")
...
       x_tasks->cancel_task();
 
+      // So that actions added _after_ cancellation will never execute
+      x_tasks->add_action(increment(x));
+
       // Cancellation supercedes resumption - nothing more happens on this task
       ccf::tasks::resume_task(std::move(resumable));
 
-      beacon.wait_for_work_with_timeout(std::chrono::milliseconds(100));
+      std::this_thread::sleep_for(std::chrono::milliseconds(100));
```
Comment (maxtropets) [inline src/tasks/test/demo/main.cpp:221]: Just for clarity.

Not sure why beacon here, because there's no `notify` for it, so it acted purely as a timeout, and so I've put an explicit timeout instead.
