### PR TITLE
Don't rollback uncommittable indices on become_follower

### LINKED ISSUE #7618: Inconsistent "Disagreement about primaries" error in `partitions_test`
Seems to be more common recently.

Example run here:
https://github.com/microsoft/CCF/actions/runs/21292229577/job/61288620224?pr=7616#step:10:361

Sample output/trace looks like this:
```
16:14:58.073 | INFO     | infra.partitions:drop:57 - Dropping rules "[0,2],[1]"
16:14:58.083 | INFO     | infra.network:wait_for_primary_unanimity:1759 - Waiting up to 75.0s for all nodes to agree on the primary in view >= 2
16:14:59.148 | INFO     | infra.network:wait_for_primary_unanimity:1777 - Primary not found for f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e
...
16:16:05.323 | INFO     | infra.network:wait_for_primary_unanimity:1777 - Primary not found for f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e
16:16:06.504 | INFO     | infra.network:wait_for_primary_unanimity:1777 - Primary not found for f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e
16:16:07.684 | INFO     | infra.network:wait_for_primary_unanimity:1777 - Primary not found for f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e
16:16:08.871 | INFO     | infra.network:wait_for_primary_unanimity:1777 - Primary not found for f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e
16:16:10.049 | INFO     | infra.network:wait_for_primary_unanimity:1777 - Primary not found for f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e
16:16:11.229 | INFO     | infra.network:wait_for_primary_unanimity:1777 - Primary not found for f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e
16:16:12.409 | INFO     | infra.network:wait_for_primary_unanimity:1777 - Primary not found for f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e
16:16:13.590 | INFO     | infra.network:wait_for_primary_unanimity:1777 - Primary not found for f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e
16:16:13.707 | INFO     | infra.network:wait_for_primary_unanimity:1783 - [1] GET /node/network
16:16:13.707 | INFO     | infra.network:wait_for_primary_unanimity:1783 - 200 @2.20 {"current_service_create_txid":"2.1","current_view":2,"primary_id":null,"recovery_count":0,"service_certificate":"-----BEGIN CERTIFICATE-----\nMIIB2DCCAV6gAwIBAgIRAIakgTMCaxHuqBdU1+b34rEwCgYIKoZIzj0EAwMwGzEZ\nMBcGA1UEAwwQQ0NGIFRlc3QgU2VydmljZTAeFw0yNjAxMjM + 616 chars
16:16:13.723 | INFO     | infra.network:wait_for_primary_unanimity:1788 - [0] GET /node/consensus
16:16:13.723 | INFO     | infra.network:wait_for_primary_unanimity:1788 - 200 {"details":{"acks":{"6cec5ed4e4a613dd3c3686b8e9d597ad74ae84a56014082cb6a798f85c1cee3b":{"last_received_ms":3,"seqno":22},"f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e":{"last_received_ms":2,"seqno":21}},"configs":[{"idx":5,"nodes":{"6ce + 520 chars
{'details': {'acks': {'6cec5ed4e4a613dd3c3686b8e9d597ad74ae84a56014082cb6a798f85c1cee3b': {'last_received_ms': 3,
                                                                                           'seqno': 22},
                      'f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e': {'last_received_ms': 2,
                                                                                           'seqno': 21}},
             'configs': [{'idx': 5,
                          'nodes': {'6cec5ed4e4a613dd3c3686b8e9d597ad74ae84a56014082cb6a798f85c1cee3b': {'address': '127.46.204.161:34199'},
                                    '8ceebccb98f83f156dbb18b55ed6cf966d3e3d53edec438f68f18b9bd106ba15': {'address': '127.226.17.114:41855'},
                                    'f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e': {'address': '127.63.78.53:40283'}},
                          'rid': 5}],
             'current_view': 2,
             'leadership_state': 'Leader',
             'membership_state': 'Active',
             'primary_id': '8ceebccb98f83f156dbb18b55ed6cf966d3e3d53edec438f68f18b9bd106ba15',
             'reconfiguration_type': 'OneTransaction',
             'ticking': True}}
16:16:13.741 | INFO     | infra.network:wait_for_primary_unanimity:1788 - [1] GET /node/consensus
16:16:13.741 | INFO     | infra.network:wait_for_primary_unanimity:1788 - 200 {"details":{"acks":{"6cec5ed4e4a613dd3c3686b8e9d597ad74ae84a56014082cb6a798f85c1cee3b":{"last_received_ms":0,"seqno":0},"8ceebccb98f83f156dbb18b55ed6cf966d3e3d53edec438f68f18b9bd106ba15":{"last_received_ms":0,"seqno":0}},"configs":[{"idx":5,"nodes":{"6cec5 + 458 chars
{'details': {'acks': {'6cec5ed4e4a613dd3c3686b8e9d597ad74ae84a56014082cb6a798f85c1cee3b': {'last_received_ms': 0,
                                                                                           'seqno': 0},
                      '8ceebccb98f83f156dbb18b55ed6cf966d3e3d53edec438f68f18b9bd106ba15': {'last_received_ms': 0,
                                                                                           'seqno': 0}},
             'configs': [{'idx': 5,
                          'nodes': {'6cec5ed4e4a613dd3c3686b8e9d597ad74ae84a56014082cb6a798f85c1cee3b': {'address': '127.46.204.161:34199'},
                                    '8ceebccb98f83f156dbb18b55ed6cf966d3e3d53edec438f68f18b9bd106ba15': {'address': '127.226.17.114:41855'},
                                    'f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e': {'address': '127.63.78.53:40283'}},
                          'rid': 5}],
             'current_view': 2,
             'leadership_state': 'Follower',
             'membership_state': 'Active',
             'primary_id': None,
             'reconfiguration_type': 'OneTransaction',
             'ticking': True}}
16:16:13.757 | INFO     | infra.network:wait_for_primary_unanimity:1788 - [2] GET /node/consensus
16:16:13.758 | INFO     | infra.network:wait_for_primary_unanimity:1788 - 200 {"details":{"acks":{"8ceebccb98f83f156dbb18b55ed6cf966d3e3d53edec438f68f18b9bd106ba15":{"last_received_ms":0,"seqno":0},"f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e":{"last_received_ms":0,"seqno":0}},"configs":[{"idx":5,"nodes":{"6cec5 + 520 chars
{'details': {'acks': {'8ceebccb98f83f156dbb18b55ed6cf966d3e3d53edec438f68f18b9bd106ba15': {'last_received_ms': 0,
                                                                                           'seqno': 0},
                      'f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e': {'last_received_ms': 0,
                                                                                           'seqno': 0}},
             'configs': [{'idx': 5,
                          'nodes': {'6cec5ed4e4a613dd3c3686b8e9d597ad74ae84a56014082cb6a798f85c1cee3b': {'address': '127.46.204.161:34199'},
                                    '8ceebccb98f83f156dbb18b55ed6cf966d3e3d53edec438f68f18b9bd106ba15': {'address': '127.226.17.114:41855'},
                                    'f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e': {'address': '127.63.78.53:40283'}},
                          'rid': 5}],
             'current_view': 2,
             'leadership_state': 'Follower',
             'membership_state': 'Active',
             'primary_id': '8ceebccb98f83f156dbb18b55ed6cf966d3e3d53edec438f68f18b9bd106ba15',
             'reconfiguration_type': 'OneTransaction',
             'ticking': True}}
16:16:13.758 | INFO     | infra.network:log_stack_traces:560 - Logging stack traces for all nodes
16:16:14.864 | ERROR    | infra.remote:log_stack_trace:222 - Stack trace of process 4377 written to /__w/CCF/CCF/build/workspace/partitions_0/stack_trace
16:16:15.964 | ERROR    | infra.remote:log_stack_trace:222 - Stack trace of process 4395 written to /__w/CCF/CCF/build/workspace/partitions_1/stack_trace
16:16:17.083 | ERROR    | infra.remote:log_stack_trace:222 - Stack trace of process 4420 written to /__w/CCF/CCF/build/workspace/partitions_2/stack_trace
16:16:17.083 | INFO     | infra.network:close_on_error:1993 - Stopping network
16:16:17.083 | INFO     | infra.node:stop:482 - Stopping node 0
16:16:17.083 | INFO     | infra.remote:stop:236 - [127.226.17.114] closing
16:16:17.198 | INFO     | infra.node:stop:482 - Stopping node 1
16:16:17.198 | INFO     | infra.remote:stop:236 - [127.63.78.53] closing
16:16:17.312 | INFO     | infra.node:stop:482 - Stopping node 2
16:16:17.312 | INFO     | infra.remote:stop:236 - [127.46.204.161] closing
16:16:17.426 | INFO     | infra.network:stop_all_nodes:1096 - All nodes stopped
16:16:17.428 | INFO     | infra.partitions:cleanup:97 - CCF-TEST iptables chain cleaned up
Traceback (most recent call last):
  File "/__w/CCF/CCF/tests/partitions_test.py", line 1118, in <module>
    run(args)
    │   └ Namespace(binary_dir='/__w/CCF/CCF/build', library_dir='/__w/CCF/CCF/build', debug_nodes=[], log_level='info', log_format_json=F...
    └ <function run at 0x78f5c819fc40>
  File "/__w/CCF/CCF/tests/partitions_test.py", line 1094, in run
    test_partition_majority(network, args)
    │                       │        └ Namespace(binary_dir='/__w/CCF/CCF/build', library_dir='/__w/CCF/CCF/build', debug_nodes=[], log_level='info', log_format_json=F...
    │                       └ <infra.network.Network object at 0x78f5f586b770>
    └ <function test_partition_majority at 0x78f5c819e7a0>
  File "/__w/CCF/CCF/tests/suite/test_requirements.py", line 22, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<infra.network.Network object at 0x78f5f586b770>, Namespace(binary_dir='/__w/CCF/CCF/build', library_dir='/__w/CCF/CCF/build', ...
           └ <function test_partition_majority at 0x78f5c819e700>
  File "/__w/CCF/CCF/tests/partitions_test.py", line 92, in test_partition_majority
    network.wait_for_primary_unanimity(min_view=initial_view)
    │                                           └ 2
    └ <infra.network.Network object at 0x78f5f586b770>
  File "/__w/CCF/CCF/tests/infra/network.py", line 1791, in wait_for_primary_unanimity
    assert all_good, f"Disagreement about primaries: {primary_opinions}"
           │                                          └ {'8ceebccb98f83f156dbb18b55ed6cf966d3e3d53edec438f68f18b9bd106ba15': '8ceebccb98f83f156dbb18b55ed6cf966d3e3d53edec438f68f18b9bd1...
           └ False
AssertionError: Disagreement about primaries: {'8ceebccb98f83f156dbb18b55ed6cf966d3e3d53edec438f68f18b9bd106ba15': '8ceebccb98f83f156dbb18b55ed6cf966d3e3d53edec438f68f18b9bd106ba15', 'f5b0a24bb9f29b4efe844615f9dc4e3df072645b45797a7f4a70468bf8cde13e': None, '6cec5ed4e4a613dd3c3686b8e9d597ad74ae84a56014082cb6a798f85c1cee3b': '8ceebccb98f83f156dbb18b55ed6cf966d3e3d53edec438f68f18b9bd106ba15'}


0% tests passed, 1 tests failed out of 1

Label Time Summary:
e2e           = 103.33 sec*proc (1 test)
partitions    = 103.33 sec*proc (1 test)

Total Test time (real) = 103.34 sec

The following tests FAILED:
	 71 - partitions (Failed)
```

### PR DESCRIPTION
**Pull request by cjen1-msft**
Closes #7618 

The hypothesis is that a backup had previously acked a regular entry, but was missing any subsequent signature, was partitioned, and became a pre-vote candidate.
When the partition was removed it received an append-entries message and became a follower again, in doing so truncating the previously acked regular entry.

From this point onwards, the backup would keep nacking the append-entries, but the leader who's `match_idx` for that replica is now higher than the last index in the ledger would never reduce the `sent_idx` past the `match_idx`, and so keep sending messages which could not be ack'd by the backup.

The solution is to remove the rollback of uncommittable entries during `become_follower`.
This leaves the `recv_append_entries` function fixup path as the only place backups truncate entries, and only until a non-fixup append-entries is received.

Additionally I've moved the `last_ack_timeout` to after the checks for a valid append_entries_response, as if a leader is unhealthy it should step-down via check-quorum, rather than keeping on being a faulty leader.

Finally I cleaned up a line number in the documentation, and made the invalid view check more explicit.

### CODE REVIEW

File: tests/raft_scenarios/follower_rollback_match_index [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+periodic_one,0,10
+dispatch_single,0,2
+dispatch_single,2,0
+
+emit_signature,2
+
+# time out b2
+periodic_one,2,100
+assert_detail,2,leadership_state,PreVoteCandidate
+drop_pending_to,2,0 # Drop pre-vote request
```
Comment (eddyashton) [inline tests/raft_scenarios/follower_rollback_match_index]: Why do we drop this? Surely with or without the fix, node 2 is calling for PreVotes _before_ the newly emitted signature, so node 0 will vote against it?

File: tests/raft_scenarios/follower_rollback_match_index [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+
+periodic_one,0,10
+dispatch_single,0,2
+dispatch_single,2,0
+
+periodic_one,0,10 
+dispatch_single,0,2
+dispatch_single,2,0
+
+state_all
```
Comment (eddyashton) [inline tests/raft_scenarios/follower_rollback_match_index]: This looks like an incomplete debugging scenario to me. We should add state/detail assertions at the end, and ideally confirm that there is a route to liveness (a few `dispatch_all`s restore a full sync. I forget if this is inserted automagically for all of the scenarios somewhere else?)

File: src/consensus/aft/raft.h [hunk 3]
```diff
@@ -1212,7 +1212,7 @@ namespace aft
           state->commit_idx);
         return;
       }
-      // Redundant with check on get_term_internal() at line 1149
+      // Redundant with check on get_term_internal() at line 1156
       // Which captures this case in every situation, except r.prev_term == 0.
       // That only happens if r.prev_idx == 0 however, see line 1033,
       // in which case this path should not be taken either.
```
Comment (eddyashton) [inline src/consensus/aft/raft.h]: I think updating line numbers is a sign that the comment is too-precise, and not helpful. I think the `1033` is _also_ out-of-date. I think we could condense it without losing any meaningful precision, while adding context on _why_ we're keeping a redundant branch.

```suggestion
// This block is redundant - the checks above cover this case, so the code inside this block should be unreachable.
// It is retained out of paranoia, in case future rewrites of the above conditions allow a fallthrough.
```

Then it's arguable whether the block should be `RAFT_FAIL_FMT` (prefer liveness, guess at correctness) or `std::unreachable` (prefer an early-warning when your refactor changes behaviour). I say this only because it's on my mind of other reasons right now. I'm pretty sure I'm the one who argued for keeping this block in the first place, so the "keep this in-case we refactor" must have been convicing.

File: src/consensus/aft/raft.h [hunk 4]
```diff
@@ -2244,11 +2246,6 @@ namespace aft
       restart_election_timeout();
       reset_last_ack_timeouts();
 
-      // Drop anything unsigned here, but retain all signed entries. Only do a
-      // more aggressive rollback, potentially including signatures, when
-      // receiving a conflicting AppendEntries
-      rollback(last_committable_index());
-
       state->leadership_state = ccf::kv::LeadershipState::Follower;
```
Comment (eddyashton) [inline src/consensus/aft/raft.h:2248]:
```suggestion
      // Note that we do _not_ eagerly rollback here, even the unsigned state. If the new primary disagrees with our suffix, we'll rollback shortly when receiving a conflicting AppendEntries
      state->leadership_state = ccf::kv::LeadershipState::Follower;
```

Not critical, but its annoying to have a deep semantic change implemented as a pure-deletion, because it is harder to find in the git history. A comment like this gestures at the historical bug, shows clearly in the `blame`, may save us a few hours in a future debugging session. Other epistemologies are available.

File: tests/raft_scenarios/follower_rollback_match_index (hunk 1 above)
Comment (cjen1-msft) [reply tests/raft_scenarios/follower_rollback_match_index]: Yep this is just such that we don't need to either a) fully partition 2, or b) run extra comms rounds.

File: tests/raft_scenarios/follower_rollback_match_index (hunk 2 above)
Comment (cjen1-msft) [reply tests/raft_scenarios/follower_rollback_match_index]: Yep every scenario adds a `loop_until_sync`
Tbh here I think you are right and we should be explicit about requiring it.

File: src/consensus/aft/raft.h (hunk 4 above)
Comment (achamayou) [reply src/consensus/aft/raft.h:2248]: Not sure I agree, adding comments that says "we don't do something here" adds clutter. I don't know that doing this has saved us time before, or if it has I don't remember it.

File: tests/raft_scenarios/follower_rollback_match_index (hunk 1 above)
Comment (achamayou) [reply tests/raft_scenarios/follower_rollback_match_index]: Making the scenario as realistic as possible is probably a good idea.

File: tests/raft_scenarios/follower_rollback_match_index (hunk 2 above)
Comment (achamayou) [reply tests/raft_scenarios/follower_rollback_match_index]: https://github.com/microsoft/CCF/blob/32a744b4c0848039ccbb5a2de7c768a39c60f1da/src/consensus/aft/test/driver.h#L1170

I think we should drop the magic that auto-inserts it, add it manually, and have a lesser bit of magic that fails scenarios that do not end on that line. We can always add another line that the validation accepts later "do_not_loop_sync_this_is_a_dead_network".

File: tests/raft_scenarios/soft_rollback [hunk 5]
```diff
@@ -55,26 +55,22 @@ state_all
 # Node 2 calls an election, advancing to term 3
 periodic_one,2,110
 
-# Node 2's RequestVote reaches Node 1, causing a soft-rollback
+# -- Node 2's RequestVote reaches Node 1, causing a soft-rollback --
+# Node 2's RequestVote reaches Node 1, causing it to advance term but not roll-back
 dispatch_one,2
 
-# Node 1 should retain the committed state!
+# Node 1 should retain the whole state 4.10 it had previously
```
Comment (achamayou) [inline tests/raft_scenarios/soft_rollback]: Any way we can assert that?

File: tla/consensus/Traceccfraft.tla [hunk 6]
```diff
@@ -202,8 +202,9 @@ IsBecomeLeader ==
     /\ Range(logline.msg.state.committable_indices) \subseteq CommittableIndices(logline.msg.state.node_id)
     /\ commitIndex[logline.msg.state.node_id] = logline.msg.state.commit_idx
     /\ leadershipState'[logline.msg.state.node_id] = ToLeadershipState[logline.msg.state.leadership_state]
-    /\ membershipState[logline.msg.state.node_id] \in ToMembershipState[logline.msg.state.membership_state]
-    /\ Len(log[logline.msg.state.node_id]) = logline.msg.state.last_idx
+    \* The log is truncated during BecomeLeader to the last committable index, and so membership state may have also changed
+    /\ membershipState'[logline.msg.state.node_id] \in ToMembershipState[logline.msg.state.membership_state]
+    /\ Len(log'[logline.msg.state.node_id]) = logline.msg.state.last_idx
```
Comment (cjen1-msft) [inline tla/consensus/Traceccfraft.tla:207]: The previous behaviour was that when becoming candidate we truncated the ledger to last committable index, and then the truncation during BecomeLeader was a no-op.
Now we only truncate during BecomeLeader, so we need to talk about the subsequent state.

File: src/consensus/aft/raft.h (hunk 4 above)
Comment (cjen1-msft) [reply src/consensus/aft/raft.h:2248]: I think as this change brings us closer to what is more commonly understood as Raft (only truncate during append entries) that no comment is necessary here.

File: tests/raft_scenarios/soft_rollback (hunk 5 above)
Comment (cjen1-msft) [reply tests/raft_scenarios/soft_rollback]: Done

File: src/consensus/aft/test/driver.h [hunk 7]
```diff
@@ -1443,4 +1443,20 @@ class RaftDriver
       }
     }
   }
+
+  void assert_last_txid(
+    const std::string& node_id, const std::string& lastTxID_s)
```
Comment (achamayou) [inline src/consensus/aft/test/driver.h]:
```suggestion
    const std::string& node_id, const std::string& last_txid_s)
```

File: src/consensus/aft/test/driver.h [hunk 8]
```diff
@@ -1443,4 +1443,20 @@ class RaftDriver
...
+  {
+    auto idx = _nodes.at(node_id).raft->get_last_idx();
+    auto view = _nodes.at(node_id).raft->get_view(idx);
+    auto lastTxID = fmt::format("{}.{}", view, idx);
```
Comment (achamayou) [inline src/consensus/aft/test/driver.h]:
```suggestion
    auto last_txid = fmt::format("{}.{}", view, idx);
```

We're reasonably consistently snake_case for variables, and I thought that was enforced by clang-format even.

File: src/consensus/aft/test/driver.h [hunk 9]
```diff
@@ -1443,4 +1443,20 @@ class RaftDriver
...
+    if (lastTxID != lastTxID_s)
+    {
+      throw std::runtime_error(fmt::format(
+        "Node {} lastTxID is not as expected: {} != {}",
+        node_id,
+        lastTxID,
+        lastTxID_s));
```
Comment (achamayou) [inline src/consensus/aft/test/driver.h]:
```suggestion
        last_txid,
        last_txid_s));
```

File: src/consensus/aft/raft.h [hunk 10]
```diff
@@ -1212,10 +1212,10 @@ namespace aft
           state->commit_idx);
         return;
       }
-      // Redundant with check on get_term_internal() at line 1149
-      // Which captures this case in every situation, except r.prev_term == 0.
-      // That only happens if r.prev_idx == 0 however, see line 1033,
-      // in which case this path should not be taken either.
+      // This block is redundant - the checks above cover this case, so the code
+      // inside this block should be unreachable. It is retained out of
+      // paranoia, in case future rewrites of the above conditions allow a
```
Comment (achamayou) [inline src/consensus/aft/raft.h]:
```suggestion
      // abundance of caution, in case future rewrites of the above conditions allow a
```

File: src/consensus/aft/test/driver.h [hunk 11]
```diff
@@ -1443,4 +1443,20 @@ class RaftDriver
       }
     }
   }
+
+  void assert_last_txid(
+    const std::string& node_id, const std::string& lastTxID_s)
+  {
+    auto idx = _nodes.at(node_id).raft->get_last_idx();
+    auto view = _nodes.at(node_id).raft->get_view(idx);
```
Comment (achamayou) [inline src/consensus/aft/test/driver.h:1451]: Hm, I wonder if this what we want vs get_term_at_index
